"""Generate canonical captions, master timeline, and isolated PrevisRoot.

New video source lives only under src/videos/V<N>/. The generated registration
imports that source graph and never imports or reads production Root.jsx.
"""

import argparse
import json
import pathlib
import re
import sys

import stage_state as state

AUTOGEN = "AUTO-GENERATED by assemble.py"
T_FADE = 15
WORDS_PER_LINE = 4
CANVAS_BG = "#E7E3D9"
INDEX_TS = ('import { registerRoot } from "remotion";\n'
            'import { PrevisRoot } from "./PrevisRoot";\n\n'
            'registerRoot(PrevisRoot);\n')


def load_plan(path):
    plan = json.loads(path.read_text(encoding="utf-8"))
    video = state.normalize_video(plan.get("video"))
    if not re.fullmatch(r"V\w+", video):
        raise ValueError(f'plan requires "video": "V<N>"; got {video!r}')
    return plan, video


def scene_parts(plan, video=None):
    video = state.normalize_video(video or plan.get("video", "V"))
    out = []
    for scene in plan.get("scenes") or []:
        transition = scene.get("transitionIn", "none")
        if transition not in ("fade", "none"):
            raise ValueError(f"{scene.get('id')}: only semantic fade/none transitions are supported")
        stem = state.scene_stem(scene.get("id"))
        component = f"{video}{stem}"
        duration = f"{video}{stem.upper()}_DURATION"
        out.append((scene.get("id"), stem, component, duration, transition))
    return out


def build_caption_lines(words_path, fps):
    words = json.loads(words_path.read_text(encoding="utf-8"))["words"]
    lines, current, segment = [], [], None
    for text, start, end, seg, *_rest in words:
        if seg != segment or len(current) >= WORDS_PER_LINE:
            if current:
                lines.append(current)
            current, segment = [], seg
        current.append({"text": text, "startFrame": round(start * fps),
                        "endFrame": round(end * fps)})
    if current:
        lines.append(current)
    return lines


def captions_js(lines):
    payload = json.dumps(lines, ensure_ascii=False, indent=2)
    return f'''// {AUTOGEN}; derived from words_aligned.json.
export const CAPTION_LINES = {payload};
'''


def shared_jsx():
    return f'''// {AUTOGEN}; canonical per-video caption presentation.
import {{useCurrentFrame}} from "remotion";
import {{CAPTION_LINES}} from "./captions";
export const Captions = () => {{
  const frame = useCurrentFrame();
  const line = CAPTION_LINES.find((item) => item.length > 0 &&
    frame >= item[0].startFrame && frame <= item[item.length - 1].endFrame + 10);
  if (!line) return null;
  return <div style={{{{position: "absolute", left: 0, right: 0, bottom: 440,
    display: "flex", justifyContent: "center", zIndex: 100, padding: "0 40px"}}}}>
    <div style={{{{backgroundColor: "rgba(20,20,20,0.85)", borderRadius: 14,
      padding: "12px 24px", display: "flex", flexWrap: "wrap", justifyContent: "center",
      gap: "0 0.32em", maxWidth: "100%"}}}}>
      {{line.map((word, index) => <span key={{index}} style={{{{fontFamily: "Arial, sans-serif",
        fontWeight: 700, fontSize: 38, lineHeight: 1.25,
        color: frame >= word.startFrame && frame <= word.endFrame + 2 ? "#FF6A1A" : "#FFFFFF",
        opacity: frame > word.endFrame + 2 ? 0.6 : 1}}}}>{{word.text}}</span>)}}
    </div>
  </div>;
}};
'''


def master_jsx(plan, video, parts):
    pads, fades = [], 0
    for index in range(len(parts)):
        fade_after = index < len(parts) - 1 and parts[index + 1][4] == "fade"
        pads.append(index == len(parts) - 1 or fade_after)
        fades += int(fade_after)
    imports = "\n".join(
        f'import {{ {component}, {duration} }} from "./scenes/{stem}";'
        for _sid, stem, component, duration, _transition in parts)
    terms = " +\n  ".join(f"({part[3]} + T)" if pads[index] else part[3]
                            for index, part in enumerate(parts))
    body = []
    for index, (_sid, _stem, component, duration, transition) in enumerate(parts):
        if index > 0 and transition == "fade":
            body.append("      <TransitionSeries.Transition presentation={fade()} "
                        "timing={linearTiming({durationInFrames: T})} />")
        rail = f"{duration} + T" if pads[index] else duration
        body.append(f"      <TransitionSeries.Sequence durationInFrames={{{rail}}}>\n"
                    f"        <{component} />\n      </TransitionSeries.Sequence>")
    audio = state.static_asset_name(video, "audio.mp3").replace("/assets/audio.mp3", "/audio.mp3")
    return f'''/** {AUTOGEN}; canonical source input/{video}/scene_plan.json. */
import {{AbsoluteFill, Audio, staticFile}} from "remotion";
import {{TransitionSeries, linearTiming}} from "@remotion/transitions";
import {{fade}} from "@remotion/transitions/fade";
{imports}
import {{Captions}} from "./shared";

const T = {T_FADE};
export const MASTER_DURATION =
  {terms} - {fades} * T;

export const Master = () => <AbsoluteFill style={{{{backgroundColor: "{CANVAS_BG}"}}}}>
  <Audio src={{staticFile("{audio}")}} />
  <TransitionSeries>
{chr(10).join(body)}
  </TransitionSeries>
  <Captions />
</AbsoluteFill>;
'''


def previs_root_tsx(plan, video, parts, project_root):
    paths = state.video_paths(project_root, video)
    built = [part for part in parts if (paths["scenes"] / f"{part[1]}.jsx").is_file()]
    has_master = paths["master"].is_file()
    header = (f"/** {AUTOGEN}. Source: input/{video}/scene_plan.json.\n"
              " * Isolated PREVIS registration; production roots are unreachable.\n */\n")
    if not built and not has_master:
        return header + "export const PrevisRoot = () => null;\n"
    imports = ['import {Composition, Folder} from "remotion";']
    imports.extend(
        f'import {{ {component}, {duration} }} from "./videos/{video}/scenes/{stem}";'
        for _sid, stem, component, duration, _transition in built)
    if has_master:
        imports.append(f'import {{Master, MASTER_DURATION}} from "./videos/{video}/Master";')
    fps = int(plan.get("fps", 30)); width = int(plan.get("width", 1080)); height = int(plan.get("height", 1920))
    body = []
    if built:
        body.append(f'    <Folder name="{video}-Scenes">')
        body.extend(f'      <Composition id="{component}" component={{{component}}} '
                    f'durationInFrames={{{duration}}} fps={{{fps}}} width={{{width}}} height={{{height}}} />'
                    for _sid, _stem, component, duration, _transition in built)
        body.append("    </Folder>")
    if has_master:
        body.append(f'    <Composition id="{video}Master" component={{Master}} '
                    f'durationInFrames={{MASTER_DURATION}} fps={{{fps}}} width={{{width}}} height={{{height}}} />')
    return header + "\n".join(imports) + "\n\nexport const PrevisRoot = () => <>\n" + \
        "\n".join(body) + "\n</>;\n"


def compare_or_write(path, content, check, force):
    current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else None
    if current == content:
        return True
    if check:
        print(f"assemble: stale/missing {path}")
        return False
    if current is not None and AUTOGEN not in current and not force:
        print(f"assemble: refusing to overwrite handwritten {path}; use --force deliberately")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"assemble: wrote {path}")
    return True


def run(plan_path, only=None, check=False, force=False):
    plan_path = pathlib.Path(plan_path).resolve()
    plan, video = load_plan(plan_path)
    root = state.project_root(plan_path); paths = state.video_paths(root, video)
    parts = scene_parts(plan, video); ok = True
    if only in (None, "captions"):
        words = state.words_path(root, plan)
        if not words.is_file():
            print(f"assemble: aligned words missing: {words}")
            ok = False
        else:
            ok = compare_or_write(paths["captions"], captions_js(
                build_caption_lines(words, int(plan.get("fps", 30)))), check, force) and ok
            ok = compare_or_write(paths["shared"], shared_jsx(), check, force) and ok
    if only in (None, "master"):
        missing = [paths["scenes"] / f"{part[1]}.jsx" for part in parts
                   if not (paths["scenes"] / f"{part[1]}.jsx").is_file()]
        if missing:
            print(f"assemble: {len(missing)} PREVIS scene source(s) not authored yet; master remains open")
            if check and any(contracts_status(plan, part[0]) != "PLAN" for part in parts
                             if paths["scenes"] / f"{part[1]}.jsx" in missing):
                ok = False
        elif not paths["captions"].is_file() or not paths["shared"].is_file():
            print(f"assemble: captions/shared missing: {paths['captions']}, {paths['shared']}"); ok = False
        else:
            ok = compare_or_write(paths["master"], master_jsx(plan, video, parts), check, force) and ok
    if only in (None, "register"):
        content = previs_root_tsx(plan, video, parts, root)
        ok = compare_or_write(paths["previs_root"], content, check, force) and ok
        ok = compare_or_write(paths["entry"], INDEX_TS, check, True) and ok
    return ok


def contracts_status(plan, scene_id):
    scene = next((item for item in plan.get("scenes") or [] if item.get("id") == scene_id), {})
    return "PLAN" if scene.get("status") in (None, "planned") else "PREVIS"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("plan", type=pathlib.Path)
    ap.add_argument("--only", choices=("captions", "master", "register"))
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    try:
        plan_path = state.project_path(state.project_root(__file__), args.plan)
        return 0 if run(plan_path, args.only, args.check, args.force) else 1
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"assemble: HARD {exc}", file=sys.stderr); return 1


if __name__ == "__main__":
    sys.exit(main())