"""
assemble.py - sinh phần CƠ KHÍ của một video từ scene_plan<N>.json.

Ba thứ trước nay viết tay mỗi video, dù 100% suy ra được từ plan + words file:

  1. src/captionData<M>.js   - phụ đề bám từ (4 từ/dòng, reset theo segment,
                               frame = round(t*fps)). M lấy từ "wordsFile".
  2. src/V<N>Master.jsx      - master timeline. Phép đệm rail của
                               TransitionSeries (SKILL.md bước 7) là nguồn lỗi
                               đã ghi nhận: đệm thiếu rail ĐẦU kéo mọi cảnh từ
                               S2 trở đi sớm nửa giây so với audio của chính nó.
  3. src/Root.jsx            - khối đăng ký composition, quản lý bằng marker.

Chạy từ GỐC dự án. Mặc định chạy cả ba bước, mỗi bước tự biết "chưa tới lúc":

    py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan13.json
    py -3 ... assemble.py input/scene_plan13.json --only captions
    py -3 ... assemble.py input/scene_plan13.json --check     # chỉ so, không ghi

- captions: ghi captionData<M>.js (+ shared<M>.jsx nếu chưa có). File viết tay
  có sẵn (V3-V11) được giữ nguyên - chỉ so nội dung, không đè.
- master:   chỉ sinh khi MỌI file cảnh trong plan đã tồn tại; thiếu cảnh nào
  thì liệt kê rồi bỏ qua (chưa tới lúc KHÁC có lỗi - bài học của cutout_gate).
- register: chèn/làm mới khối giữa hai marker ASSEMBLE:V<N> trong Root.jsx;
  cảnh nào đã được đăng ký tay bên ngoài khối thì không đăng ký lại.

Transition: mặc định cắt thẳng. Chỉ khai "transitionIn": "fade" khi quan hệ
giữa hai cảnh thật sự cần giữ cảm giác liên tục; "none" vẫn được chấp nhận như
tên cũ của cắt thẳng.
Muốn thứ gì cầu kỳ hơn thì viết master bằng tay - và file tay KHÔNG BAO GIỜ
bị script này đè: mọi file sinh ra đều mang dấu AUTO-GENERATED, gặp file
không có dấu là dừng (trừ khi --force).

--check thoát 1 khi file trên đĩa lệch với bản sinh lại từ plan - dùng để
phát hiện master/captions bị sửa tay lệch khỏi hợp đồng.
"""

import argparse
import json
import pathlib
import re
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except AttributeError:
    pass

AUTOGEN = "AUTO-GENERATED by assemble.py"
T_FADE = 15          # khung; khớp mọi master đã ship
WORDS_PER_LINE = 4   # khớp captionData3..11 đã ship
CANVAS_BG = "#E7E3D9"


def die(msg):
    print(f"assemble: {msg}")
    sys.exit(1)


def load_plan(path):
    plan = json.loads(path.read_text(encoding="utf-8"))
    video = plan.get("video", "")
    m = re.fullmatch(r"V(\w+)", video)
    if not m:
        die(f'plan thiếu "video": "V<N>" (đang là {video!r})')
    n = m.group(1)
    words_file = plan.get("wordsFile", "")
    wm = re.search(r"words(\w+?)_aligned\.json$", words_file)
    if not wm:
        die(f'plan thiếu "wordsFile" dạng input/words<M>_aligned.json (đang là {words_file!r})')
    return plan, n, wm.group(1), pathlib.Path(words_file)


def scene_parts(plan, n):
    """[(id, component, duration_const, transition_in)] theo thứ tự plan."""
    out = []
    for s in plan["scenes"]:
        num = s["id"].lstrip("S")
        tin = s.get("transitionIn", "none")
        if tin not in ("fade", "none"):
            die(f'{s["id"]}: transitionIn={tin!r} - chỉ hỗ trợ "fade"/"none"; '
                "kiểu khác thì viết master bằng tay")
        out.append((s["id"], f"V{n}Scene{num}", f"V{n}SCENE{num.upper()}_DURATION", tin))
    return out


# ---------------------------------------------------------------- captions

def build_caption_lines(words_path, fps):
    words = json.loads(words_path.read_text(encoding="utf-8"))["words"]
    lines, cur, cur_seg = [], [], None
    for text, start, end, seg in words:
        if seg != cur_seg or len(cur) >= WORDS_PER_LINE:
            if cur:
                lines.append(cur)
            cur, cur_seg = [], seg
        cur.append({"text": text,
                    "startFrame": round(start * fps),
                    "endFrame": round(end * fps)})
    if cur:
        lines.append(cur)
    return lines


def caption_js(m, lines):
    return (f"// {AUTOGEN} - sinh lại từ plan, đừng sửa tay.\n"
            f"export const CAPTION_LINES{m} = "
            + json.dumps(lines, ensure_ascii=False, indent=2) + ";\n")


def parse_caption_js(text):
    s = text[text.index("export const"):].split("=", 1)[1].strip().rstrip(";").rstrip()
    return json.loads(s)


SHARED_TEMPLATE = '''import {{ fontFamily, ORANGE }} from "./shared";
import {{ CAPTION_LINES{m} }} from "../captionData{m}";
import {{ useCurrentFrame }} from "remotion";

// {autogen} - dây phụ đề riêng của video, cùng mẫu shared9..11.
// Mọi primitive thật (Hero, Support, ...) vẫn là bản chuẩn trong ./shared.
export const Captions{m} = () => {{
  const frame = useCurrentFrame();
  const activeLineIndex = CAPTION_LINES{m}.findIndex((line) => {{
    if (!line || line.length === 0) return false;
    const start = line[0].startFrame;
    const end = line[line.length - 1].endFrame + 10;
    return frame >= start && frame <= end;
  }});

  if (activeLineIndex === -1) return null;
  const line = CAPTION_LINES{m}[activeLineIndex];

  return (
    <div
      style={{{{
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 440,
        display: "flex",
        justifyContent: "center",
        pointerEvents: "none",
        zIndex: 100,
        padding: "0 40px",
      }}}}
    >
      <div
        style={{{{
          backgroundColor: "rgba(20,20,20,0.85)",
          borderRadius: 14,
          padding: "12px 24px",
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "center",
          gap: "0 0.32em",
          maxWidth: "100%",
          boxShadow: "0 6px 20px rgba(0,0,0,0.25)",
        }}}}
      >
        {{line.map((w, i) => {{
          const isActive = frame >= w.startFrame && frame <= w.endFrame + 2;
          const isPast = frame > w.endFrame + 2;
          return (
            <span
              key={{i}}
              style={{{{
                fontFamily,
                fontWeight: 700,
                fontSize: 38,
                lineHeight: 1.25,
                color: isActive ? ORANGE : "#FFFFFF",
                opacity: isPast ? 0.6 : 1,
              }}}}
            >
              {{w.text}}
            </span>
          );
        }})}}
      </div>
    </div>
  );
}};
'''


def step_captions(plan, n, m, words_path, check, force):
    fps = plan.get("fps", 30)
    if not words_path.exists():
        print(f"captions: chưa có {words_path} - bỏ qua (chưa tới lúc).")
        return True
    lines = build_caption_lines(words_path, fps)
    data_path = pathlib.Path(f"src/captionData{m}.js")
    shared_path = pathlib.Path(f"src/scenes/shared{m}.jsx")

    if data_path.exists():
        old = data_path.read_text(encoding="utf-8")
        same = parse_caption_js(old) == lines
        if check:
            if not same:
                theirs, ours = parse_caption_js(old), lines
                print(f"captions: {data_path} LỆCH bản sinh từ {words_path} "
                      f"({len(theirs)} dòng trên đĩa / {len(ours)} dòng sinh ra).")
                return False
            print(f"captions: {data_path} khớp bản sinh ({len(lines)} dòng).")
            return True
        if AUTOGEN not in old and not force:
            if same:
                print(f"captions: {data_path} viết tay nhưng khớp nội dung - giữ nguyên.")
                return True
            print(f"captions: {data_path} viết tay và LỆCH bản sinh - giữ nguyên "
                  "(dùng --force nếu thật sự muốn thay).")
            return True
    if check:
        print(f"captions: {data_path} chưa tồn tại - sẽ được sinh ({len(lines)} dòng).")
        return True

    data_path.write_text(caption_js(m, lines), encoding="utf-8")
    print(f"captions: đã ghi {data_path} ({len(lines)} dòng).")
    if not shared_path.exists():
        shared_path.write_text(SHARED_TEMPLATE.format(m=m, autogen=AUTOGEN), encoding="utf-8")
        print(f"captions: đã ghi {shared_path} (Captions{m}).")
    return True


# ------------------------------------------------------------------ master

def master_jsx(plan, n, m, parts):
    audio = plan.get("audioFile", f"audio{m}.mp3")
    # rail k đệm đúng thời lượng transition ĐỨNG SAU nó; rail cuối đệm T làm
    # đuôi thở (khớp mọi master đã ship). "none" ở cảnh k+1 = không transition
    # sau cảnh k = rail k không đệm.
    pads = []
    n_fades = 0
    for i in range(len(parts)):
        if i == len(parts) - 1:
            pads.append(True)
        else:
            fade_after = parts[i + 1][3] == "fade"
            pads.append(fade_after)
            n_fades += fade_after

    imports = "\n".join(f'import {{ {c}, {d} }} from "./scenes/{c}";'
                        for _, c, d, _t in parts)
    dur_terms = " +\n  ".join(f"({d} + T)" if pads[i] else f"{d}"
                              for i, (_, _c, d, _t) in enumerate(parts))
    body = []
    for i, (_, comp, dur, _t) in enumerate(parts):
        if i > 0 and parts[i][3] == "fade":
            body.append("      <TransitionSeries.Transition presentation={fade()} "
                        "timing={linearTiming({ durationInFrames: T })} />")
        rail = f"{dur} + T" if pads[i] else dur
        body.append(f"      <TransitionSeries.Sequence durationInFrames={{{rail}}}>\n"
                    f"        <{comp} />\n"
                    f"      </TransitionSeries.Sequence>")
    return f'''/**
 * V{n}Master - master timeline, {AUTOGEN} từ input/scene_plan{n}.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan{n}.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import {{ AbsoluteFill, Audio, staticFile }} from "remotion";
import {{ TransitionSeries, linearTiming }} from "@remotion/transitions";
import {{ fade }} from "@remotion/transitions/fade";

{imports}
import {{ Captions{m} }} from "./scenes/shared{m}";

const T = {T_FADE};

export const MASTER{n}_DURATION =
  {dur_terms} - {n_fades} * T;

export const V{n}Master = () => (
  <AbsoluteFill style={{{{ backgroundColor: "{CANVAS_BG}" }}}}>
    <Audio src={{staticFile("{audio}")}} />

    <TransitionSeries>
{chr(10).join(body)}
    </TransitionSeries>

    {{/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}}
    <Captions{m} />
  </AbsoluteFill>
);
'''


def step_master(plan, n, m, parts, check, force):
    missing = [c for _, c, _d, _t in parts
               if not pathlib.Path(f"src/scenes/{c}.jsx").exists()]
    if missing:
        print(f"master: còn {len(missing)} cảnh chưa dựng ({', '.join(missing[:5])}"
              f"{'...' if len(missing) > 5 else ''}) - bỏ qua (chưa tới lúc).")
        return True
    shared_path = pathlib.Path(f"src/scenes/shared{m}.jsx")
    if not shared_path.exists():
        print(f"master: thiếu {shared_path} (Captions{m}) - chạy bước captions trước.")
        return False

    content = master_jsx(plan, n, m, parts)
    path = pathlib.Path(f"src/V{n}Master.jsx")
    if check:
        if not path.exists():
            print(f"master: {path} chưa được sinh dù mọi cảnh đã dựng - chạy assemble.")
            return False
        old = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if old != content:
            print(f"master: {path} LỆCH bản sinh từ plan - rail/cảnh đã bị sửa tay "
                  "lệch khỏi hợp đồng. Sinh lại bằng assemble, đừng vá tay.")
            return False
        print(f"master: {path} khớp bản sinh ({len(parts)} cảnh).")
        return True
    if path.exists() and AUTOGEN not in path.read_text(encoding="utf-8") and not force:
        print(f"master: {path} là file viết tay, không đè (dùng --force nếu chắc chắn).")
        return False
    path.write_text(content, encoding="utf-8")
    print(f"master: đã ghi {path} ({len(parts)} cảnh, {n_fades_msg(parts)}).")
    return True


def n_fades_msg(parts):
    n_fades = sum(1 for p in parts[1:] if p[3] == "fade")
    cuts = len(parts) - 1 - n_fades
    return f"{n_fades} fade" + (f", {cuts} cắt thẳng" if cuts else "")


# ---------------------------------------------------------------- register

IMP_MARK = "// ===== ASSEMBLE:V{n} imports - khối máy sinh, đừng sửa tay ====="
IMP_END = "// ===== /ASSEMBLE:V{n} imports ====="
COMP_MARK = "      {{/* ===== ASSEMBLE:V{n} - khối máy sinh, đừng sửa tay ===== */}}"
COMP_END = "      {{/* ===== /ASSEMBLE:V{n} ===== */}}"


def _splice(text, start_mark, end_mark, block, insert_before):
    """Thay nội dung giữa 2 marker; chưa có marker thì chèn trước insert_before."""
    if start_mark in text:
        pre = text[:text.index(start_mark)]
        rest = text[text.index(end_mark) + len(end_mark):]
        if not block:
            return pre.rstrip("\n") + "\n" + rest.lstrip("\n")
        return pre + start_mark + "\n" + block + "\n" + end_mark + rest
    if not block:
        return text
    i = text.index(insert_before)
    return (text[:i] + start_mark + "\n" + block + "\n" + end_mark + "\n\n"
            + text[i:])


def _outside_block(text, start_mark, end_mark):
    if start_mark not in text:
        return text
    return (text[:text.index(start_mark)]
            + text[text.index(end_mark) + len(end_mark):])


def build_register_blocks(root_text, n, parts, canvas="LUATSU_CANVAS"):
    imp_mark, imp_end = IMP_MARK.format(n=n), IMP_END.format(n=n)
    comp_mark, comp_end = COMP_MARK.format(n=n), COMP_END.format(n=n)
    outside_imp = _outside_block(root_text, imp_mark, imp_end)
    outside_comp = _outside_block(root_text, comp_mark, comp_end)

    built = [(c, d) for _, c, d, _t in parts
             if pathlib.Path(f"src/scenes/{c}.jsx").exists()]
    imp_lines, comp_lines = [], []
    for comp, dur in built:
        if f'from "./scenes/{comp}"' not in outside_imp:
            imp_lines.append(f'import {{ {comp}, {dur} }} from "./scenes/{comp}";')
        if f'id="{comp}"' not in outside_comp:
            comp_lines.append(
                f'        <Composition id="{comp}" component={{{comp}}} '
                f"durationInFrames={{{dur}}} fps={{{canvas}.fps}} "
                f"width={{{canvas}.width}} height={{{canvas}.height}} />")
    if comp_lines:
        comp_lines = ([f'      <Folder name="V{n}-Scenes">'] + comp_lines + ["      </Folder>"])

    master_path = pathlib.Path(f"src/V{n}Master.jsx")
    if master_path.exists():
        if f'from "./V{n}Master"' not in outside_imp:
            imp_lines.append(
                f'import {{ V{n}Master, MASTER{n}_DURATION }} from "./V{n}Master";')
        if f'id="V{n}Master"' not in outside_comp:
            comp_lines.append(
                f'      <Composition id="V{n}Master" component={{V{n}Master}} '
                f"durationInFrames={{MASTER{n}_DURATION}} fps={{{canvas}.fps}} "
                f"width={{{canvas}.width}} height={{{canvas}.height}} />")
    return "\n".join(imp_lines), "\n".join(comp_lines)


def step_register(plan, n, parts, check, root_path=pathlib.Path("src/Root.jsx")):
    if not root_path.exists():
        print(f"register: không thấy {root_path} - chạy từ gốc dự án.")
        return False
    text = root_path.read_text(encoding="utf-8")
    imp_block, comp_block = build_register_blocks(text, n, parts)
    new = _splice(text, IMP_MARK.format(n=n), IMP_END.format(n=n), imp_block,
                  "export const RemotionRoot")
    new = _splice(new, COMP_MARK.format(n=n), COMP_END.format(n=n), comp_block,
                  "    </>")
    if new == text:
        print("register: Root.jsx đã đúng, không có gì để thêm.")
        return True
    if check:
        print("register: Root.jsx LỆCH - còn composition chưa đăng ký hoặc khối "
              "marker cũ. Chạy assemble để làm mới.")
        return False
    root_path.write_text(new, encoding="utf-8")
    added = (imp_block.count("import") if imp_block else 0)
    print(f"register: đã cập nhật {root_path} ({added} import trong khối ASSEMBLE:V{n}).")
    return True


# -------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", type=pathlib.Path)
    ap.add_argument("--only", choices=["captions", "master", "register"])
    ap.add_argument("--check", action="store_true",
                    help="chỉ so với bản sinh lại, không ghi; thoát 1 nếu lệch")
    ap.add_argument("--force", action="store_true",
                    help="cho phép đè file không mang dấu AUTO-GENERATED")
    args = ap.parse_args()

    if not args.plan.exists():
        die(f"không thấy {args.plan}")
    plan, n, m, words_path = load_plan(args.plan)
    parts = scene_parts(plan, n)

    ok = True
    if args.only in (None, "captions"):
        ok = step_captions(plan, n, m, words_path, args.check, args.force) and ok
    if args.only in (None, "master"):
        ok = step_master(plan, n, m, parts, args.check, args.force) and ok
    if args.only in (None, "register"):
        ok = step_register(plan, n, parts, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
