"""Canonical PROMOTE timing resolver for meaning-bearing beats.

Fresh PLAN stores anchor phrases, not authored frames. This resolver maps those
phrases through words_aligned.json to scene-local frames and emits the one
generated timing module imported by promoted scene source. Ambient camera motion
does not enter this contract. A manual beat is legal only as ``manual — reason``;
its actual frame remains an explicit source-level editorial override.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import unicodedata

import stage_state as state

VERSION = "anchor-phrase-promotion-v1"
MANUAL = re.compile(r"^manual\s*[—-]\s*(.+)$", re.I)


def normalize(value):
    value = unicodedata.normalize("NFKC", str(value or "")).lower()
    return " ".join(re.sub(r"[^\w]+", " ", value, flags=re.UNICODE).split())


def load_words(path):
    return json.loads(pathlib.Path(path).read_text(encoding="utf-8"))["words"]


def find_phrase(words, phrase, scene_start=None, scene_end=None):
    target = normalize(phrase).split()
    flattened = []
    for word in words:
        if scene_start is not None and float(word[1]) < float(scene_start):
            continue
        if scene_end is not None and float(word[1]) >= float(scene_end):
            continue
        for token in normalize(word[0]).split():
            flattened.append((token, word))
    for index in range(len(flattened) - len(target) + 1):
        if [item[0] for item in flattened[index:index + len(target)]] == target:
            return flattened[index][1], flattened[index + len(target) - 1][1]
    return None


def to_frame(seconds, scene_start, fps):
    return int(round((float(seconds) - float(scene_start)) * int(fps)))


def beat_id(scene, material, index):
    material_id = material.get("id") or material.get("name") or f"material-{index + 1}"
    return f"{scene.get('id')}:{material_id}"


def resolve_plan(plan, words):
    fps = int(plan.get("fps", 30))
    resolved = {}
    manual = {}
    for scene in plan.get("scenes") or []:
        start, end = float(scene.get("startSec", 0)), float(scene.get("endSec", 0))
        for index, material in enumerate(state.scene_materials(scene)):
            phrase = str(material.get("anchorPhrase") or "").strip()
            if not phrase:
                continue
            key = beat_id(scene, material, index)
            override = MANUAL.match(phrase)
            if override:
                reason = override.group(1).strip()
                if len(reason) < 8:
                    raise ValueError(f"{key}: manual beat reason is too vague")
                manual[key] = reason
                continue
            match = find_phrase(words, phrase, start, end)
            if not match:
                raise ValueError(f"{key}: anchorPhrase {phrase!r} not found inside scene")
            resolved[key] = {"frame": to_frame(match[0][1], start, fps),
                             "anchorPhrase": phrase,
                             "spokenStartSec": float(match[0][1]),
                             "spokenEndSec": float(match[1][2])}
    return {"version": VERSION, "fps": fps, "beats": resolved, "manual": manual}


def timing_js(contract):
    frames = {key: item["frame"] for key, item in sorted(contract["beats"].items())}
    payload = json.dumps(frames, ensure_ascii=False, indent=2)
    return (f"// AUTO-GENERATED by beat_sync.py; {VERSION}. Do not hand-edit.\n"
            f"export const PROMOTION_TIMING = Object.freeze({payload});\n")


def resolve_contract(plan_path):
    plan_path = pathlib.Path(plan_path).resolve()
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    root = state.project_root(plan_path)
    words = load_words(state.words_path(root, plan))
    return plan, root, resolve_plan(plan, words)


def write_timing(plan_path, check=False):
    plan, root, contract = resolve_contract(plan_path)
    path = state.video_paths(root, plan.get("video", "V"))["timing"]
    expected = timing_js(contract)
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if check:
        if current != expected:
            raise ValueError(f"promotion timing is stale or missing: {path}")
    elif current != expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    return path, contract


def resolve_evidence_regions(plan, words):
    result = []
    for scene in plan.get("scenes") or []:
        for index, material in enumerate(state.scene_materials(scene)):
            regions = []
            for mapping in material.get("evidenceRegions") or []:
                match = find_phrase(words, mapping["anchorPhrase"], scene.get("startSec"), scene.get("endSec"))
                if not match:
                    raise ValueError(f"{beat_id(scene, material, index)}: evidence region anchor not found")
                x, y, width, height = mapping["region"]
                regions.append({"from": to_frame(match[0][1], scene.get("startSec"), plan.get("fps", 30)),
                                "x": x, "y": y, "width": width, "height": height})
            if regions:
                result.append({"scene": scene.get("id"), "material": material.get("id"),
                               "regions": regions})
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    resolve = sub.add_parser("resolve-plan")
    resolve.add_argument("plan"); resolve.add_argument("--check", action="store_true")
    regions = sub.add_parser("evidence-regions")
    regions.add_argument("plan")
    frame = sub.add_parser("frame")
    frame.add_argument("words"); frame.add_argument("--scene-start", required=True, type=float)
    frame.add_argument("--scene-end", type=float); frame.add_argument("--phrase", required=True)
    frame.add_argument("--fps", type=int, default=30)
    args = parser.parse_args()
    try:
        if args.command == "resolve-plan":
            path, contract = write_timing(args.plan, args.check)
            print(json.dumps({"path": str(path), **contract}, ensure_ascii=False, indent=2)); return 0
        if args.command == "evidence-regions":
            plan_path = pathlib.Path(args.plan).resolve()
            plan = json.loads(plan_path.read_text(encoding="utf-8"))
            words = load_words(state.words_path(state.project_root(plan_path), plan))
            print(json.dumps(resolve_evidence_regions(plan, words), ensure_ascii=False, indent=2)); return 0
        match = find_phrase(load_words(args.words), args.phrase, args.scene_start, args.scene_end)
        if not match:
            raise ValueError(f"anchorPhrase {args.phrase!r} not found")
        print(to_frame(match[0][1], args.scene_start, args.fps)); return 0
    except (OSError, KeyError, ValueError, json.JSONDecodeError) as exc:
        print(f"beat_sync: HARD {exc}", file=sys.stderr); return 1


if __name__ == "__main__":
    sys.exit(main())