"""Deterministic specification tests for the canonical PREVIS-in-place workflow."""

import argparse
import copy
import json
import pathlib
import subprocess
import sys
import tempfile

import assemble
import build_gate
import hook_gate
import pipeline_contracts as contracts
import render_review_sheet
import render_video
import stage_state as state

HERE = pathlib.Path(__file__).resolve().parent
ROOT = state.project_root(__file__)


def image(path, color, mark=(30, 30, 180, 300)):
    from PIL import Image, ImageDraw
    path.parent.mkdir(parents=True, exist_ok=True)
    value = Image.new("RGB", (270, 480), color)
    ImageDraw.Draw(value).rectangle(mark, fill=(255, 106, 26))
    value.save(path)


def plan_gate_stub(*_args, **_kwargs):
    return type("PlanGateResult", (), {"returncode": 0, "stdout": "", "stderr": ""})()


def fixture(tmp):
    (tmp / "input").mkdir(); (tmp / "public").mkdir(); (tmp / "src").mkdir()
    (tmp / "package.json").write_text(json.dumps({"dependencies": {
        "remotion": "4.0.507", "@remotion/cli": "4.0.507"}}), encoding="utf-8")
    (tmp / "package-lock.json").write_text(json.dumps({"lockfileVersion": 3, "packages": {
        "node_modules/remotion": {"version": "4.0.507"},
        "node_modules/@remotion/cli": {"version": "4.0.507"}}}), encoding="utf-8")
    video = "V99"; paths = state.video_paths(tmp, video)
    for directory in (paths["input"], paths["assets"], paths["scenes"], paths["previs_frames"],
                      paths["promoted_previs_frames"], paths["receipts"], paths["output"] / "draft",
                      paths["review_dir"], paths["output"] / "final"):
        directory.mkdir(parents=True, exist_ok=True)
    paths["words"].write_text(json.dumps({"words": [["evidence", 0, 1, 0]]}), encoding="utf-8")
    paths["audio"].parent.mkdir(parents=True, exist_ok=True); paths["audio"].write_bytes(b"audio")
    asset = paths["assets"] / "doc.png"; asset.write_bytes(b"locked-document")
    plan = {
        "video": video, "fps": 30, "wordsFile": "input/V99/words_aligned.json",
        "audioFile": "V99/audio.mp3", "status": "active", "shotlistApproved": True,
        "globalVisualContract": {"palette": "paper-orange", "bespoke": True},
        "scenes": [{
            "id": "S1", "startSec": 0, "endSec": 2, "durationInFrames": 60,
            "masterStartFrame": 0, "status": "previs", "narrativeFunction": "evidence",
            "viewerQuestion": "What proves the claim?",
            "visualTransformation": "the authentic record opens, then its decisive region takes focus",
            "contrastWithPrevious": "opening documentary proof", "visualLanguage": "document",
            "backdrop": "paper", "variant": "focus", "density": "med",
            "comprehensionLoad": "moderate",
            "assetRationale": "The authentic record is the meaning-bearing proof.",
            "assets": [{"name": "Court record", "src": "doc.png", "role": "document",
                        "meaningBearing": True, "locked": True,
                        "lockedSha256": state.hash_file(asset),
                        "selectionRationale": "The authentic record is the meaning-bearing proof.",
                        "evidenceIdentity": "court-record-page-1",
                        "evidenceRegions": [{"anchorPhrase": "evidence", "region": [0.1, 0.2, 0.7, 0.2]}],
                        "delay": 0, "visibleFor": 60, "describes": ["evidence"]}],
            "visualEvents": [{"frame": 0, "what": "document opens"}],
            "punch": {"lines": [], "anchorPhrase": "", "from": 0,
                      "describes": [], "visibleFor": 0},
        }],
    }
    state.write_json(paths["plan"], plan)
    source = paths["scenes"] / "S01.jsx"
    source.write_text('import {Img, staticFile} from "remotion";\n'
                      'export const V99S01_DURATION=60;\n'
                      'export const V99S01=()=> <Img src={staticFile("V99/assets/doc.png")} '
                      'style={{opacity:1, transform:"translateX(0px)"}}/>;\n', encoding="utf-8")
    paths["captions"].write_text('// AUTO-GENERATED by assemble.py\nexport const Captions=()=>null;', encoding="utf-8")
    paths["master"].write_text('// AUTO-GENERATED by assemble.py\nexport const MASTER_DURATION=60; '
                               'export const Master=()=>null;', encoding="utf-8")
    paths["entry"].write_text('import {registerRoot} from "remotion"; import {PrevisRoot} '
                              'from "./PrevisRoot"; registerRoot(PrevisRoot);', encoding="utf-8")
    paths["previs_root"].write_text(
        '/** AUTO-GENERATED by assemble.py */\nimport {Composition} from "remotion"; '
        'import {Master,MASTER_DURATION} from "./videos/V99/Master"; '
        'export const PrevisRoot=()=> <Composition id="V99Master" component={Master} '
        'durationInFrames={MASTER_DURATION} fps={30} width={1080} height={1920}/>;', encoding="utf-8")
    (tmp / "remotion.config.ts").write_text("export default {};", encoding="utf-8")
    open_frame, key_frame = paths["previs_frames"] / "S01_OPEN.png", paths["previs_frames"] / "S01_KEY.png"
    image(open_frame, (18, 18, 16)); image(key_frame, (18, 18, 16), (90, 80, 240, 330))
    image(paths["contact_sheet"], (30, 30, 30))
    state.write_json(paths["previs_manifest"], {
        "schema": 1, "video": video, "contactSheet": str(paths["contact_sheet"]),
        "contactSheetSha256": state.hash_file(paths["contact_sheet"]), "frames": [
            {"scene": "S1", "role": "OPEN", "localFrame": 0, "path": str(open_frame),
             "sha256": state.hash_file(open_frame), "sourcePath": str(source),
             "sourceSha256": state.hash_file(source)},
            {"scene": "S1", "role": "KEY", "localFrame": 30, "path": str(key_frame),
             "sha256": state.hash_file(key_frame), "sourcePath": str(source),
             "sourceSha256": state.hash_file(source)}]})
    promoted_open = paths["promoted_previs_frames"] / "S01_OPEN.png"
    promoted_key = paths["promoted_previs_frames"] / "S01_KEY.png"
    promoted_open.write_bytes(open_frame.read_bytes()); promoted_key.write_bytes(key_frame.read_bytes())
    state.write_json(paths["promoted_previs_manifest"], {
        "schema": 1, "video": video, "frames": [
            {"scene": "S1", "role": "OPEN", "localFrame": 0, "path": str(promoted_open),
             "sha256": state.hash_file(promoted_open)},
            {"scene": "S1", "role": "KEY", "localFrame": 30, "path": str(promoted_key),
             "sha256": state.hash_file(promoted_key)}]})
    return plan, paths, source, asset


def approve(plan_path):
    return contracts.approve_previs(plan_path, None, "human approved composition")


def close_plan(plan_path):
    plan = state.read_json(plan_path, {})
    state.make_receipt(contracts.plan_receipt_path(plan_path, plan), "editorial-plan",
                       contracts.plan_inputs(plan_path, plan), contracts.plan_tool(), {},
                       outputs=(), accepted={"manual": True})


def checks(tmp):
    results = []
    plan, paths, source, asset = fixture(tmp)
    plan_path = paths["plan"]

    # Canonical layout / isolation / exact gate surface.
    results.append(("canonical paths: input/public/source/out/runtime", all((
        paths["plan"] == tmp / "input/V99/scene_plan.json",
        paths["public"] == tmp / "public/V99", paths["assets"] == tmp / "public/V99/assets",
        paths["source"] == tmp / "src/videos/V99", paths["scenes"] == tmp / "src/videos/V99/scenes",
        paths["draft"] == tmp / "out/V99/draft/master.mp4",
        paths["final"] == tmp / "out/V99/final/master.mp4",
        paths["receipts"] == tmp / "input/.videoagent/V99/receipts"))))
    results.append(("exactly six unconditional REQUIRED_GATES",
                    hook_gate.REQUIRED_GATES == ("plan_gate.py", "build_gate.py", "text_gate.py",
                                                 "assemble.py", "review_gate.py", "selftest.py")))
    index = (ROOT / "src/index.ts").read_text(encoding="utf-8")
    results.append(("PrevisRoot isolation: index has no production Root dependency",
                    "PrevisRoot" in index and "Root.jsx" not in index and 'from "./Root"' not in index))

    # PLAN and PREVIS authoring legal before approval.
    plan_only = copy.deepcopy(plan); plan_only["shotlistApproved"] = False
    plan_only["scenes"][0]["status"] = "planned"
    state.write_json(plan_path, plan_only)
    plan_proc = subprocess.run([sys.executable, str(HERE / "plan_gate.py"), str(plan_path), "--hook"],
                               capture_output=True, text=True, encoding="utf-8", errors="replace")
    results.append(("semantic PLAN works before PREVIS",
                    not contracts.lifecycle_contract(plan_only)["anyPrevis"] and plan_proc.returncode == 0))
    state.write_json(plan_path, plan)
    close_plan(plan_path)
    source_problems, checked = build_gate.previs_source_check(plan_path, plan)
    results.append(("PREVIS authoring works before human PREVIS approval",
                    checked == 1 and not source_problems))

    # Direct bespoke staticFile and mounted presence.
    results.append(("direct staticFile locked asset identity passes",
                    "doc.png" in build_gate.static_file_references(source.read_text(encoding="utf-8"))))
    absent = source.read_text(encoding="utf-8").replace('staticFile("V99/assets/doc.png")',
                                                        'staticFile("V99/assets/other.png")')
    source.write_text(absent, encoding="utf-8")
    failed, _ = build_gate.previs_source_check(plan_path, plan)
    results.append(("removed direct staticFile hard fails", any("absent" in item for item in failed)))
    source.write_text('import {Img,Sequence,staticFile} from "remotion"; export const V99S01=()=> '
                      '<Sequence from={30}><Img src={staticFile("V99/assets/doc.png")}/></Sequence>;',
                      encoding="utf-8")
    drift, _comparisons = build_gate.previs_baseline_check(
        plan_path, plan, paths["previs_manifest"], paths["promoted_previs_manifest"])
    results.append(("late Sequence approved-element regression blocks",
                    any("absent at approved frame" in item for item in drift)))
    source.write_text('import {Img,staticFile} from "remotion"; export const V99S01=()=> '
                      '<Img src={staticFile("V99/assets/doc.png")} '
                      'style={{opacity:0.4,transform:"translateY(10px)"}}/>;', encoding="utf-8")
    mounted, _comparisons = build_gate.previs_baseline_check(
        plan_path, plan, paths["previs_manifest"], paths["promoted_previs_manifest"])
    results.append(("mounted opacity/transform approved-element case passes",
                    not any("absent at approved frame" in item for item in mounted)))

    manifest = state.read_json(paths["previs_manifest"], {})
    missing_key = copy.deepcopy(manifest); missing_key["frames"] = [missing_key["frames"][0]]
    missing_key_path = paths["previs"] / "missing-key.json"; state.write_json(missing_key_path, missing_key)
    try:
        contracts.validate_previs_manifest(plan_path, plan, missing_key_path)
        key_blocked = False
    except ValueError as exc:
        key_blocked = "KEY" in str(exc)
    results.append(("approve-previs contract requires OPEN and KEY", key_blocked))
    missing_contact = copy.deepcopy(manifest); missing_contact["contactSheet"] = str(paths["previs"] / "absent.png")
    missing_contact_path = paths["previs"] / "missing-contact.json"; state.write_json(missing_contact_path, missing_contact)
    try:
        contracts.validate_previs_manifest(plan_path, plan, missing_contact_path)
        contact_blocked = False
    except ValueError as exc:
        contact_blocked = "contact sheet" in str(exc)
    results.append(("approve-previs contract requires whole-video contact sheet", contact_blocked))

    close_plan(plan_path)
    try:
        approve(plan_path)
        stale_source_blocked = False
    except ValueError as exc:
        stale_source_blocked = "stale against current scene source" in str(exc)
    results.append(("new approval rejects pixels stale against scene source", stale_source_blocked))
    manifest = state.read_json(paths["previs_manifest"], {})
    for item in manifest["frames"]:
        item["sourcePath"] = str(source); item["sourceSha256"] = state.hash_file(source)
    state.write_json(paths["previs_manifest"], manifest)

    # Creative approval currentness.
    close_plan(plan_path); approve(plan_path)
    results.append(("approve-previs receipt is current", contracts.previs_is_closed(plan_path)[0]))
    source_before_motion = source.read_text(encoding="utf-8")
    source.write_text(source_before_motion + "\n// additive motion implementation", encoding="utf-8")
    results.append(("post-approval JSX byte change is provenance-only",
                    contracts.previs_is_closed(plan_path)[0]))
    source.write_text(source_before_motion, encoding="utf-8")
    timing = state.read_json(plan_path, {}); timing["scenes"][0]["startSec"] = 0.2
    timing["scenes"][0]["endSec"] = 2.2; timing["scenes"][0]["durationInFrames"] = 66
    timing["scenes"][0]["masterStartFrame"] = 6; timing["scenes"][0]["transitionIn"] = "fade"
    state.write_json(plan_path, timing)
    results.append(("timing-only creative mutation remains CURRENT",
                    contracts.previs_is_closed(plan_path)[0]))
    semantic = copy.deepcopy(timing); semantic["scenes"][0]["visualTransformation"] += " materially changed"
    state.write_json(plan_path, semantic)
    results.append(("visualTransformation mutation makes approval STALE",
                    not contracts.previs_is_closed(plan_path)[0]))
    state.write_json(plan_path, timing)
    evidence = copy.deepcopy(timing); evidence["scenes"][0]["assets"][0]["evidenceRegions"][0]["region"] = [0.2, 0.2, 0.6, 0.2]
    state.write_json(plan_path, evidence)
    results.append(("evidence-region mutation makes approval STALE",
                    not contracts.previs_is_closed(plan_path)[0]))
    state.write_json(plan_path, timing); asset.write_bytes(b"swapped-asset-bytes")
    results.append(("locked asset byte mutation makes approval STALE",
                    not contracts.previs_is_closed(plan_path)[0]))
    asset.write_bytes(b"locked-document"); state.write_json(plan_path, plan)
    close_plan(plan_path); approve(plan_path)

    # Promoted drift and draft boundary.
    problems, _ = build_gate.previs_baseline_check(
        plan_path, plan, paths["previs_manifest"], paths["promoted_previs_manifest"])
    results.append(("promoted matching OPEN/KEY conformance passes", not problems))
    tool = state.tool_identity(HERE / "build_gate.py", versions={"baseline": build_gate.PIXEL_VERSION})
    state.make_receipt(build_gate.baseline_receipt_path(tmp, "V99"), "previs-conformance",
                       build_gate.baseline_inputs(plan_path, plan, paths["previs_manifest"],
                                                  paths["promoted_previs_manifest"]),
                       tool, {}, outputs=())
    command = render_video.render_contract(plan_path, "draft")[9]
    results.append(("valid approved/conformed draft reaches command generation",
                    command[:5] == ["npx", "remotion", "render", "src/index.ts", "V99Master"]))
    approval_path = paths["receipts"] / "previs-approved.json"; approval_bytes = approval_path.read_bytes()
    approval_path.unlink()
    try:
        render_video.render_contract(plan_path, "draft")
        blocked = False
    except ValueError as exc:
        blocked = "draft blocked before Remotion" in str(exc)
    results.append(("draft without approve-previs is blocked before Remotion", blocked))
    approval_path.write_bytes(approval_bytes)
    image(paths["promoted_previs_frames"] / "S01_OPEN.png", (240, 240, 240), (0, 0, 20, 20))
    stale, _ = build_gate.previs_baseline_check(
        plan_path, plan, paths["previs_manifest"], paths["promoted_previs_manifest"])
    results.append(("promoted approved-pixel drift blocks", any("approved-pixel drift" in x for x in stale)))
    try:
        render_video.render_contract(plan_path, "draft")
        stale_draft = False
    except ValueError as exc:
        stale_draft = "conformance" in str(exc)
    results.append(("promoted pixel mutation invalidates draft command", stale_draft))

    # PREVIS request/manifest mechanics and registration generation.
    requests = render_review_sheet.previs_requests(plan, paths)
    results.append(("PREVIS requests require OPEN/KEY and no undeclared MID",
                    [item["role"] for item in requests] == ["OPEN", "KEY"] and
                    all(item["composition"] == "V99S01" for item in requests)))
    generated_root = assemble.previs_root_tsx(plan, "V99", assemble.scene_parts(plan, "V99"), tmp)
    results.append(("generated registration targets src/videos/V99 only",
                    "./videos/V99/" in generated_root and "Root.jsx" not in generated_root))

    # Deleted architecture stays absent and packet CLIs stay removed.
    deleted = ("scene_plan" + "_check.py", "generate" + "_sfx.py",
               "baseline" + "_gate.py", "block" + "_gate.py",
               "asset" + "_gate.py", "pixel" + "_gate.py")
    results.append(("confirmed legacy scripts are absent", all(not (HERE / name).exists() for name in deleted)))
    contract_source = (HERE / "pipeline_contracts.py").read_text(encoding="utf-8")
    results.append(("worker-packet and asset-brief-packet CLIs are absent",
                    "worker-packet" not in contract_source and "asset-brief-packet" not in contract_source))
    all_active = "\n".join(path.read_text(encoding="utf-8", errors="ignore")
                           for path in HERE.glob("*.py") if path.name != pathlib.Path(__file__).name)
    results.append(("deleted gates are not referenced by active scripts",
                    all(name not in all_active for name in deleted)))

    # Active document geometry contract.
    geometry = tmp / "geometry-test.mjs"
    module = (ROOT / "src/scenes/documentEvidenceGeometry.mjs").as_uri()
    geometry.write_text(
        f'import {{fitDocumentEvidence as fit}} from {json.dumps(module)};\n'
        'const cases=[{x:.2,y:.2,width:.5,height:.3},{x:0,y:.2,width:.35,height:.3},'
        '{x:.65,y:.2,width:.35,height:.3},{x:.3,y:0,width:.3,height:1},'
        '{x:0,y:.4,width:1,height:.15}];\n'
        'const ok=cases.every(region=>{const g=fit({viewportWidth:960,viewportHeight:1120,'
        'sourceAspect:.707,region,requestedZoom:2.4,safetyMargin:18});return '
        'g.focusLeft>=18-1e-6&&g.focusTop>=18-1e-6&&g.focusLeft+g.focusWidth<=942+1e-6&&'
        'g.focusTop+g.focusHeight<=1102+1e-6;});process.exit(ok?0:1);', encoding="utf-8")
    proc = subprocess.run(["node", str(geometry)], capture_output=True, text=True)
    results.append(("DocumentEvidence geometry remains safe", proc.returncode == 0))
    return results


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-v", "--verbose", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()
    with tempfile.TemporaryDirectory(prefix="previs-spec-") as directory:
        try:
            results = checks(pathlib.Path(directory))
        except Exception as exc:  # noqa: BLE001
            results = [("selftest completed without crashing", False, f"{type(exc).__name__}: {exc}")]
    normalized = [(item[0], item[1], item[2] if len(item) > 2 else "") for item in results]
    failed = [item for item in normalized if not item[1]]
    if args.json:
        print(json.dumps({"passed": not failed, "cases": [
            {"name": name, "ok": ok, "detail": detail} for name, ok, detail in normalized]}, indent=2))
    else:
        for name, ok, detail in normalized:
            print(f"{'OK  ' if ok else 'FAIL'} {name}")
            if detail:
                print(f"     {detail}")
        print(f"\n{'PASSED' if not failed else 'FAILED'} "
              f"({len(normalized) - len(failed)}/{len(normalized)} specification checks)")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())