// AUTO-GENERATED by assemble.py - sinh lại từ plan, đừng sửa tay.
export const CAPTION_LINES13 = [
  [
    {
      "text": "Như",
      "startFrame": 0,
      "endFrame": 6
    },
    {
      "text": "tiêu",
      "startFrame": 6,
      "endFrame": 12
    },
    {
      "text": "đề",
      "startFrame": 12,
      "endFrame": 17
    },
    {
      "text": "thì",
      "startFrame": 17,
      "endFrame": 23
    }
  ],
  [
    {
      "text": "hôm",
      "startFrame": 23,
      "endFrame": 29
    },
    {
      "text": "nay",
      "startFrame": 29,
      "endFrame": 35
    },
    {
      "text": "chúng",
      "startFrame": 35,
      "endFrame": 40
    },
    {
      "text": "ta",
      "startFrame": 40,
      "endFrame": 46
    }
  ],
  [
    {
      "text": "sẽ",
      "startFrame": 46,
      "endFrame": 52
    },
    {
      "text": "nói",
      "startFrame": 52,
      "endFrame": 58
    },
    {
      "text": "về",
      "startFrame": 58,
      "endFrame": 63
    },
    {
      "text": "những",
      "startFrame": 63,
      "endFrame": 69
    }
  ],
  [
    {
      "text": "cái",
      "startFrame": 69,
      "endFrame": 75
    },
    {
      "text": "hiện",
      "startFrame": 75,
      "endFrame": 81
    },
    {
      "text": "tượng",
      "startFrame": 81,
      "endFrame": 87
    },
    {
      "text": "khoa",
      "startFrame": 87,
      "endFrame": 92
    }
  ],
  [
    {
      "text": "học",
      "startFrame": 92,
      "endFrame": 98
    },
    {
      "text": "khá",
      "startFrame": 98,
      "endFrame": 104
    },
    {
      "text": "là",
      "startFrame": 104,
      "endFrame": 110
    },
    {
      "text": "khó",
      "startFrame": 110,
      "endFrame": 115
    }
  ],
  [
    {
      "text": "giải",
      "startFrame": 115,
      "endFrame": 121
    },
    {
      "text": "thích",
      "startFrame": 121,
      "endFrame": 127
    },
    {
      "text": "và",
      "startFrame": 127,
      "endFrame": 133
    },
    {
      "text": "một",
      "startFrame": 133,
      "endFrame": 138
    }
  ],
  [
    {
      "text": "số",
      "startFrame": 138,
      "endFrame": 144
    },
    {
      "text": "cái",
      "startFrame": 144,
      "endFrame": 150
    },
    {
      "text": "thậm",
      "startFrame": 150,
      "endFrame": 156
    },
    {
      "text": "chí",
      "startFrame": 156,
      "endFrame": 162
    }
  ],
  [
    {
      "text": "nghe",
      "startFrame": 162,
      "endFrame": 167
    },
    {
      "text": "còn",
      "startFrame": 167,
      "endFrame": 173
    },
    {
      "text": "hơi",
      "startFrame": 173,
      "endFrame": 179
    },
    {
      "text": "bị",
      "startFrame": 179,
      "endFrame": 185
    }
  ],
  [
    {
      "text": "siêu",
      "startFrame": 185,
      "endFrame": 190
    },
    {
      "text": "nhiên.",
      "startFrame": 190,
      "endFrame": 196
    }
  ],
  [
    {
      "text": "Nhưng",
      "startFrame": 196,
      "endFrame": 202
    },
    {
      "text": "mà",
      "startFrame": 202,
      "endFrame": 207
    },
    {
      "text": "không",
      "startFrame": 207,
      "endFrame": 212
    },
    {
      "text": "hẳn",
      "startFrame": 212,
      "endFrame": 218
    }
  ],
  [
    {
      "text": "là",
      "startFrame": 218,
      "endFrame": 223
    },
    {
      "text": "phi",
      "startFrame": 223,
      "endFrame": 229
    },
    {
      "text": "khoa",
      "startFrame": 229,
      "endFrame": 234
    },
    {
      "text": "học,",
      "startFrame": 234,
      "endFrame": 239
    }
  ],
  [
    {
      "text": "mà",
      "startFrame": 239,
      "endFrame": 245
    },
    {
      "text": "kiểu",
      "startFrame": 245,
      "endFrame": 250
    },
    {
      "text": "khoa",
      "startFrame": 250,
      "endFrame": 256
    },
    {
      "text": "học",
      "startFrame": 256,
      "endFrame": 261
    }
  ],
  [
    {
      "text": "cũng",
      "startFrame": 261,
      "endFrame": 266
    },
    {
      "text": "kiểu",
      "startFrame": 266,
      "endFrame": 272
    }
  ],
  [
    {
      "text": "không",
      "startFrame": 272,
      "endFrame": 278
    },
    {
      "text": "biết",
      "startFrame": 278,
      "endFrame": 285
    },
    {
      "text": "giải",
      "startFrame": 285,
      "endFrame": 292
    },
    {
      "text": "thích",
      "startFrame": 292,
      "endFrame": 298
    }
  ],
  [
    {
      "text": "thế",
      "startFrame": 298,
      "endFrame": 305
    },
    {
      "text": "nào",
      "startFrame": 305,
      "endFrame": 312
    },
    {
      "text": "ấy.",
      "startFrame": 312,
      "endFrame": 318
    },
    {
      "text": "Ok,",
      "startFrame": 318,
      "endFrame": 325
    }
  ],
  [
    {
      "text": "bắt",
      "startFrame": 325,
      "endFrame": 332
    },
    {
      "text": "đầu",
      "startFrame": 332,
      "endFrame": 338
    },
    {
      "text": "thôi!",
      "startFrame": 338,
      "endFrame": 345
    }
  ],
  [
    {
      "text": "Đầu",
      "startFrame": 345,
      "endFrame": 351
    },
    {
      "text": "tiên",
      "startFrame": 351,
      "endFrame": 357
    },
    {
      "text": "là",
      "startFrame": 357,
      "endFrame": 364
    },
    {
      "text": "Vua",
      "startFrame": 364,
      "endFrame": 370
    }
  ],
  [
    {
      "text": "chuột",
      "startFrame": 370,
      "endFrame": 376
    },
    {
      "text": "hay",
      "startFrame": 376,
      "endFrame": 382
    },
    {
      "text": "là",
      "startFrame": 382,
      "endFrame": 388
    },
    {
      "text": "Rat",
      "startFrame": 388,
      "endFrame": 395
    }
  ],
  [
    {
      "text": "King.",
      "startFrame": 395,
      "endFrame": 401
    }
  ],
  [
    {
      "text": "Đây",
      "startFrame": 411,
      "endFrame": 416
    },
    {
      "text": "là",
      "startFrame": 416,
      "endFrame": 421
    },
    {
      "text": "một",
      "startFrame": 421,
      "endFrame": 426
    },
    {
      "text": "hiện",
      "startFrame": 426,
      "endFrame": 431
    }
  ],
  [
    {
      "text": "tượng",
      "startFrame": 431,
      "endFrame": 436
    },
    {
      "text": "khá",
      "startFrame": 436,
      "endFrame": 441
    },
    {
      "text": "là",
      "startFrame": 441,
      "endFrame": 446
    },
    {
      "text": "hiếm",
      "startFrame": 446,
      "endFrame": 451
    }
  ],
  [
    {
      "text": "gặp",
      "startFrame": 451,
      "endFrame": 456
    },
    {
      "text": "ở",
      "startFrame": 456,
      "endFrame": 461
    },
    {
      "text": "chuột,",
      "startFrame": 461,
      "endFrame": 466
    },
    {
      "text": "đặc",
      "startFrame": 466,
      "endFrame": 470
    }
  ],
  [
    {
      "text": "biệt",
      "startFrame": 470,
      "endFrame": 475
    },
    {
      "text": "là",
      "startFrame": 475,
      "endFrame": 480
    },
    {
      "text": "ở",
      "startFrame": 480,
      "endFrame": 485
    },
    {
      "text": "chuột",
      "startFrame": 485,
      "endFrame": 490
    }
  ],
  [
    {
      "text": "đen",
      "startFrame": 490,
      "endFrame": 495
    },
    {
      "text": "hay",
      "startFrame": 495,
      "endFrame": 500
    },
    {
      "text": "còn",
      "startFrame": 500,
      "endFrame": 505
    },
    {
      "text": "gọi",
      "startFrame": 505,
      "endFrame": 510
    }
  ],
  [
    {
      "text": "là",
      "startFrame": 510,
      "endFrame": 515
    },
    {
      "text": "chuột",
      "startFrame": 515,
      "endFrame": 520
    },
    {
      "text": "Tàu.",
      "startFrame": 520,
      "endFrame": 525
    }
  ],
  [
    {
      "text": "Và",
      "startFrame": 525,
      "endFrame": 530
    },
    {
      "text": "không,",
      "startFrame": 530,
      "endFrame": 535
    },
    {
      "text": "đây",
      "startFrame": 535,
      "endFrame": 540
    },
    {
      "text": "không",
      "startFrame": 540,
      "endFrame": 545
    }
  ],
  [
    {
      "text": "phải",
      "startFrame": 545,
      "endFrame": 550
    },
    {
      "text": "là",
      "startFrame": 550,
      "endFrame": 555
    },
    {
      "text": "một",
      "startFrame": 555,
      "endFrame": 560
    },
    {
      "text": "con",
      "startFrame": 560,
      "endFrame": 565
    }
  ],
  [
    {
      "text": "chuột",
      "startFrame": 565,
      "endFrame": 570
    },
    {
      "text": "đột",
      "startFrame": 570,
      "endFrame": 575
    },
    {
      "text": "biến",
      "startFrame": 575,
      "endFrame": 580
    },
    {
      "text": "xong",
      "startFrame": 580,
      "endFrame": 585
    }
  ],
  [
    {
      "text": "rồi",
      "startFrame": 585,
      "endFrame": 591
    },
    {
      "text": "đi",
      "startFrame": 591,
      "endFrame": 596
    },
    {
      "text": "dạy",
      "startFrame": 596,
      "endFrame": 601
    },
    {
      "text": "võ",
      "startFrame": 601,
      "endFrame": 606
    }
  ],
  [
    {
      "text": "cho",
      "startFrame": 606,
      "endFrame": 611
    },
    {
      "text": "bốn",
      "startFrame": 611,
      "endFrame": 616
    },
    {
      "text": "con",
      "startFrame": 616,
      "endFrame": 621
    },
    {
      "text": "rùa.",
      "startFrame": 621,
      "endFrame": 626
    }
  ],
  [
    {
      "text": "Vua",
      "startFrame": 626,
      "endFrame": 632
    },
    {
      "text": "chuột",
      "startFrame": 632,
      "endFrame": 638
    },
    {
      "text": "là",
      "startFrame": 638,
      "endFrame": 645
    },
    {
      "text": "khi",
      "startFrame": 645,
      "endFrame": 651
    }
  ],
  [
    {
      "text": "mà",
      "startFrame": 651,
      "endFrame": 657
    },
    {
      "text": "nhiều",
      "startFrame": 657,
      "endFrame": 663
    },
    {
      "text": "con",
      "startFrame": 663,
      "endFrame": 670
    },
    {
      "text": "chuột",
      "startFrame": 670,
      "endFrame": 676
    }
  ],
  [
    {
      "text": "bị",
      "startFrame": 676,
      "endFrame": 682
    },
    {
      "text": "mắc",
      "startFrame": 682,
      "endFrame": 689
    },
    {
      "text": "đuôi",
      "startFrame": 689,
      "endFrame": 695
    },
    {
      "text": "vào",
      "startFrame": 695,
      "endFrame": 701
    }
  ],
  [
    {
      "text": "nhau,",
      "startFrame": 701,
      "endFrame": 707
    }
  ],
  [
    {
      "text": "và",
      "startFrame": 707,
      "endFrame": 712
    },
    {
      "text": "đuôi",
      "startFrame": 712,
      "endFrame": 717
    },
    {
      "text": "của",
      "startFrame": 717,
      "endFrame": 722
    },
    {
      "text": "chúng",
      "startFrame": 722,
      "endFrame": 726
    }
  ],
  [
    {
      "text": "nó",
      "startFrame": 726,
      "endFrame": 731
    },
    {
      "text": "thì",
      "startFrame": 731,
      "endFrame": 736
    },
    {
      "text": "xoắn",
      "startFrame": 736,
      "endFrame": 741
    },
    {
      "text": "lại",
      "startFrame": 741,
      "endFrame": 745
    }
  ],
  [
    {
      "text": "thành",
      "startFrame": 745,
      "endFrame": 750
    },
    {
      "text": "một",
      "startFrame": 750,
      "endFrame": 755
    },
    {
      "text": "cái",
      "startFrame": 755,
      "endFrame": 760
    },
    {
      "text": "cục",
      "startFrame": 760,
      "endFrame": 764
    }
  ],
  [
    {
      "text": "đến",
      "startFrame": 764,
      "endFrame": 769
    },
    {
      "text": "mức",
      "startFrame": 769,
      "endFrame": 774
    },
    {
      "text": "mà",
      "startFrame": 774,
      "endFrame": 779
    },
    {
      "text": "cả",
      "startFrame": 779,
      "endFrame": 784
    }
  ],
  [
    {
      "text": "đám",
      "startFrame": 784,
      "endFrame": 789
    },
    {
      "text": "gần",
      "startFrame": 789,
      "endFrame": 794
    },
    {
      "text": "như",
      "startFrame": 794,
      "endFrame": 798
    },
    {
      "text": "là",
      "startFrame": 798,
      "endFrame": 803
    }
  ],
  [
    {
      "text": "không",
      "startFrame": 803,
      "endFrame": 808
    },
    {
      "text": "thể",
      "startFrame": 808,
      "endFrame": 813
    },
    {
      "text": "tách",
      "startFrame": 813,
      "endFrame": 818
    },
    {
      "text": "ra,",
      "startFrame": 818,
      "endFrame": 823
    }
  ],
  [
    {
      "text": "và",
      "startFrame": 823,
      "endFrame": 828
    },
    {
      "text": "cũng",
      "startFrame": 828,
      "endFrame": 833
    },
    {
      "text": "không",
      "startFrame": 833,
      "endFrame": 838
    },
    {
      "text": "thể",
      "startFrame": 838,
      "endFrame": 843
    }
  ],
  [
    {
      "text": "di",
      "startFrame": 843,
      "endFrame": 848
    },
    {
      "text": "chuyển",
      "startFrame": 848,
      "endFrame": 853
    },
    {
      "text": "bình",
      "startFrame": 853,
      "endFrame": 858
    },
    {
      "text": "thường.",
      "startFrame": 858,
      "endFrame": 863
    }
  ],
  [
    {
      "text": "Và",
      "startFrame": 863,
      "endFrame": 869
    },
    {
      "text": "một",
      "startFrame": 869,
      "endFrame": 875
    },
    {
      "text": "Vua",
      "startFrame": 875,
      "endFrame": 881
    },
    {
      "text": "chuột",
      "startFrame": 881,
      "endFrame": 886
    }
  ],
  [
    {
      "text": "có",
      "startFrame": 886,
      "endFrame": 892
    },
    {
      "text": "thể",
      "startFrame": 892,
      "endFrame": 898
    },
    {
      "text": "bao",
      "startFrame": 898,
      "endFrame": 904
    },
    {
      "text": "gồm",
      "startFrame": 904,
      "endFrame": 909
    }
  ],
  [
    {
      "text": "từ",
      "startFrame": 909,
      "endFrame": 915
    },
    {
      "text": "vài",
      "startFrame": 915,
      "endFrame": 921
    },
    {
      "text": "con",
      "startFrame": 921,
      "endFrame": 927
    },
    {
      "text": "cho",
      "startFrame": 927,
      "endFrame": 932
    }
  ],
  [
    {
      "text": "tới",
      "startFrame": 932,
      "endFrame": 938
    },
    {
      "text": "vài",
      "startFrame": 938,
      "endFrame": 944
    },
    {
      "text": "chục",
      "startFrame": 944,
      "endFrame": 949
    },
    {
      "text": "con.",
      "startFrame": 949,
      "endFrame": 955
    }
  ]
];
