// AUTO-GENERATED by assemble.py - sinh lại từ plan, đừng sửa tay.
export const CAPTION_LINES18 = [
  [
    {
      "text": "Nhưng",
      "startFrame": 0,
      "endFrame": 6
    },
    {
      "text": "câu",
      "startFrame": 6,
      "endFrame": 12
    },
    {
      "text": "chuyện",
      "startFrame": 12,
      "endFrame": 18
    },
    {
      "text": "chưa",
      "startFrame": 18,
      "endFrame": 24
    }
  ],
  [
    {
      "text": "dừng",
      "startFrame": 24,
      "endFrame": 30
    },
    {
      "text": "ở",
      "startFrame": 30,
      "endFrame": 37
    },
    {
      "text": "đó.",
      "startFrame": 37,
      "endFrame": 43
    },
    {
      "text": "Anh",
      "startFrame": 43,
      "endFrame": 49
    }
  ],
  [
    {
      "text": "T",
      "startFrame": 49,
      "endFrame": 55
    },
    {
      "text": "bị",
      "startFrame": 55,
      "endFrame": 61
    },
    {
      "text": "đưa",
      "startFrame": 61,
      "endFrame": 67
    },
    {
      "text": "đến",
      "startFrame": 67,
      "endFrame": 73
    }
  ],
  [
    {
      "text": "một",
      "startFrame": 73,
      "endFrame": 79
    },
    {
      "text": "kho",
      "startFrame": 79,
      "endFrame": 85
    },
    {
      "text": "tập",
      "startFrame": 85,
      "endFrame": 91
    },
    {
      "text": "kết",
      "startFrame": 91,
      "endFrame": 97
    }
  ],
  [
    {
      "text": "phế",
      "startFrame": 97,
      "endFrame": 104
    },
    {
      "text": "liệu.",
      "startFrame": 104,
      "endFrame": 110
    },
    {
      "text": "Tại",
      "startFrame": 110,
      "endFrame": 116
    },
    {
      "text": "đây,",
      "startFrame": 116,
      "endFrame": 122
    }
  ],
  [
    {
      "text": "anh",
      "startFrame": 122,
      "endFrame": 128
    },
    {
      "text": "tiếp",
      "startFrame": 128,
      "endFrame": 134
    },
    {
      "text": "tục",
      "startFrame": 134,
      "endFrame": 140
    },
    {
      "text": "bị",
      "startFrame": 140,
      "endFrame": 146
    }
  ],
  [
    {
      "text": "trói,",
      "startFrame": 146,
      "endFrame": 152
    },
    {
      "text": "bị",
      "startFrame": 152,
      "endFrame": 158
    },
    {
      "text": "khóa",
      "startFrame": 158,
      "endFrame": 164
    },
    {
      "text": "còng,",
      "startFrame": 164,
      "endFrame": 170
    }
  ],
  [
    {
      "text": "bị",
      "startFrame": 170,
      "endFrame": 177
    },
    {
      "text": "giữ",
      "startFrame": 177,
      "endFrame": 183
    },
    {
      "text": "lại",
      "startFrame": 183,
      "endFrame": 189
    },
    {
      "text": "để",
      "startFrame": 189,
      "endFrame": 195
    }
  ],
  [
    {
      "text": "không",
      "startFrame": 195,
      "endFrame": 201
    },
    {
      "text": "thể",
      "startFrame": 201,
      "endFrame": 207
    },
    {
      "text": "bỏ",
      "startFrame": 207,
      "endFrame": 213
    },
    {
      "text": "trốn.",
      "startFrame": 213,
      "endFrame": 219
    }
  ],
  [
    {
      "text": "N",
      "startFrame": 219,
      "endFrame": 225
    },
    {
      "text": "và",
      "startFrame": 225,
      "endFrame": 231
    },
    {
      "text": "đồng",
      "startFrame": 231,
      "endFrame": 237
    },
    {
      "text": "bọn",
      "startFrame": 237,
      "endFrame": 244
    }
  ],
  [
    {
      "text": "liên",
      "startFrame": 244,
      "endFrame": 250
    },
    {
      "text": "tục",
      "startFrame": 250,
      "endFrame": 256
    },
    {
      "text": "gây",
      "startFrame": 256,
      "endFrame": 262
    },
    {
      "text": "áp",
      "startFrame": 262,
      "endFrame": 268
    }
  ],
  [
    {
      "text": "lực,",
      "startFrame": 268,
      "endFrame": 274
    },
    {
      "text": "buộc",
      "startFrame": 274,
      "endFrame": 280
    },
    {
      "text": "anh",
      "startFrame": 280,
      "endFrame": 286
    },
    {
      "text": "T",
      "startFrame": 286,
      "endFrame": 292
    }
  ],
  [
    {
      "text": "phải",
      "startFrame": 292,
      "endFrame": 298
    },
    {
      "text": "gọi",
      "startFrame": 298,
      "endFrame": 304
    },
    {
      "text": "về",
      "startFrame": 304,
      "endFrame": 311
    },
    {
      "text": "cho",
      "startFrame": 311,
      "endFrame": 317
    }
  ],
  [
    {
      "text": "gia",
      "startFrame": 317,
      "endFrame": 323
    },
    {
      "text": "đình,",
      "startFrame": 323,
      "endFrame": 329
    }
  ],
  [
    {
      "text": "người",
      "startFrame": 349,
      "endFrame": 355
    },
    {
      "text": "thân",
      "startFrame": 355,
      "endFrame": 362
    },
    {
      "text": "tìm",
      "startFrame": 362,
      "endFrame": 368
    },
    {
      "text": "cách",
      "startFrame": 368,
      "endFrame": 375
    }
  ],
  [
    {
      "text": "chuyển",
      "startFrame": 375,
      "endFrame": 381
    },
    {
      "text": "tiền",
      "startFrame": 381,
      "endFrame": 388
    },
    {
      "text": "để",
      "startFrame": 388,
      "endFrame": 394
    },
    {
      "text": "trả",
      "startFrame": 394,
      "endFrame": 401
    }
  ],
  [
    {
      "text": "khoản",
      "startFrame": 401,
      "endFrame": 407
    },
    {
      "text": "nợ",
      "startFrame": 407,
      "endFrame": 414
    },
    {
      "text": "150",
      "startFrame": 414,
      "endFrame": 420
    },
    {
      "text": "triệu",
      "startFrame": 420,
      "endFrame": 427
    }
  ],
  [
    {
      "text": "đồng",
      "startFrame": 427,
      "endFrame": 433
    },
    {
      "text": "cho",
      "startFrame": 433,
      "endFrame": 440
    },
    {
      "text": "N",
      "startFrame": 440,
      "endFrame": 446
    },
    {
      "text": "thì",
      "startFrame": 446,
      "endFrame": 453
    }
  ],
  [
    {
      "text": "mới",
      "startFrame": 453,
      "endFrame": 459
    },
    {
      "text": "được",
      "startFrame": 459,
      "endFrame": 466
    },
    {
      "text": "thả.",
      "startFrame": 466,
      "endFrame": 472
    },
    {
      "text": "Thậm",
      "startFrame": 472,
      "endFrame": 479
    }
  ],
  [
    {
      "text": "chí",
      "startFrame": 479,
      "endFrame": 485
    },
    {
      "text": "đến",
      "startFrame": 485,
      "endFrame": 492
    },
    {
      "text": "trưa",
      "startFrame": 492,
      "endFrame": 498
    },
    {
      "text": "hôm",
      "startFrame": 498,
      "endFrame": 505
    }
  ],
  [
    {
      "text": "sau,",
      "startFrame": 505,
      "endFrame": 511
    },
    {
      "text": "N",
      "startFrame": 511,
      "endFrame": 518
    },
    {
      "text": "còn",
      "startFrame": 518,
      "endFrame": 524
    },
    {
      "text": "yêu",
      "startFrame": 524,
      "endFrame": 531
    }
  ],
  [
    {
      "text": "cầu",
      "startFrame": 531,
      "endFrame": 537
    },
    {
      "text": "anh",
      "startFrame": 537,
      "endFrame": 544
    },
    {
      "text": "T",
      "startFrame": 544,
      "endFrame": 550
    },
    {
      "text": "gọi",
      "startFrame": 550,
      "endFrame": 557
    }
  ],
  [
    {
      "text": "về",
      "startFrame": 557,
      "endFrame": 563
    },
    {
      "text": "nhà,",
      "startFrame": 563,
      "endFrame": 570
    }
  ],
  [
    {
      "text": "nói",
      "startFrame": 584,
      "endFrame": 591
    },
    {
      "text": "gia",
      "startFrame": 591,
      "endFrame": 598
    },
    {
      "text": "đình",
      "startFrame": 598,
      "endFrame": 606
    },
    {
      "text": "phải",
      "startFrame": 606,
      "endFrame": 613
    }
  ],
  [
    {
      "text": "chuyển",
      "startFrame": 613,
      "endFrame": 620
    },
    {
      "text": "đủ",
      "startFrame": 620,
      "endFrame": 627
    },
    {
      "text": "150",
      "startFrame": 627,
      "endFrame": 634
    },
    {
      "text": "triệu",
      "startFrame": 634,
      "endFrame": 641
    }
  ],
  [
    {
      "text": "đồng",
      "startFrame": 641,
      "endFrame": 648
    },
    {
      "text": "vào",
      "startFrame": 648,
      "endFrame": 655
    },
    {
      "text": "tài",
      "startFrame": 655,
      "endFrame": 662
    },
    {
      "text": "khoản",
      "startFrame": 662,
      "endFrame": 669
    }
  ],
  [
    {
      "text": "của",
      "startFrame": 669,
      "endFrame": 676
    },
    {
      "text": "anh",
      "startFrame": 676,
      "endFrame": 683
    },
    {
      "text": "T.",
      "startFrame": 683,
      "endFrame": 690
    }
  ],
  [
    {
      "text": "Những",
      "startFrame": 706,
      "endFrame": 713
    },
    {
      "text": "ngày",
      "startFrame": 713,
      "endFrame": 719
    },
    {
      "text": "sau",
      "startFrame": 719,
      "endFrame": 726
    },
    {
      "text": "đó,",
      "startFrame": 726,
      "endFrame": 733
    }
  ],
  [
    {
      "text": "việc",
      "startFrame": 733,
      "endFrame": 739
    },
    {
      "text": "giữ",
      "startFrame": 739,
      "endFrame": 746
    },
    {
      "text": "người",
      "startFrame": 746,
      "endFrame": 753
    },
    {
      "text": "và",
      "startFrame": 753,
      "endFrame": 759
    }
  ],
  [
    {
      "text": "ép",
      "startFrame": 759,
      "endFrame": 766
    },
    {
      "text": "chuyển",
      "startFrame": 766,
      "endFrame": 773
    },
    {
      "text": "tiền",
      "startFrame": 773,
      "endFrame": 779
    },
    {
      "text": "vẫn",
      "startFrame": 779,
      "endFrame": 786
    }
  ],
  [
    {
      "text": "tiếp",
      "startFrame": 786,
      "endFrame": 793
    },
    {
      "text": "diễn.",
      "startFrame": 793,
      "endFrame": 799
    },
    {
      "text": "Nghe",
      "startFrame": 799,
      "endFrame": 806
    },
    {
      "text": "đến",
      "startFrame": 806,
      "endFrame": 813
    }
  ],
  [
    {
      "text": "đây,",
      "startFrame": 813,
      "endFrame": 819
    },
    {
      "text": "nhiều",
      "startFrame": 819,
      "endFrame": 826
    },
    {
      "text": "anh",
      "startFrame": 826,
      "endFrame": 833
    },
    {
      "text": "em",
      "startFrame": 833,
      "endFrame": 839
    }
  ],
  [
    {
      "text": "chắc",
      "startFrame": 839,
      "endFrame": 846
    },
    {
      "text": "sẽ",
      "startFrame": 846,
      "endFrame": 853
    },
    {
      "text": "thắc",
      "startFrame": 853,
      "endFrame": 859
    },
    {
      "text": "mắc:",
      "startFrame": 859,
      "endFrame": 866
    }
  ],
  [
    {
      "text": "Ủa",
      "startFrame": 883,
      "endFrame": 890
    },
    {
      "text": "Lóng",
      "startFrame": 890,
      "endFrame": 896
    },
    {
      "text": "ơi.",
      "startFrame": 896,
      "endFrame": 902
    },
    {
      "text": "150",
      "startFrame": 902,
      "endFrame": 909
    }
  ],
  [
    {
      "text": "triệu",
      "startFrame": 909,
      "endFrame": 915
    },
    {
      "text": "đó",
      "startFrame": 915,
      "endFrame": 921
    },
    {
      "text": "đúng",
      "startFrame": 921,
      "endFrame": 928
    },
    {
      "text": "là",
      "startFrame": 928,
      "endFrame": 934
    }
  ],
  [
    {
      "text": "khoản",
      "startFrame": 934,
      "endFrame": 940
    },
    {
      "text": "nợ",
      "startFrame": 940,
      "endFrame": 947
    },
    {
      "text": "anh",
      "startFrame": 947,
      "endFrame": 953
    },
    {
      "text": "T",
      "startFrame": 953,
      "endFrame": 959
    }
  ],
  [
    {
      "text": "chưa",
      "startFrame": 959,
      "endFrame": 966
    },
    {
      "text": "trả",
      "startFrame": 966,
      "endFrame": 972
    },
    {
      "text": "cho",
      "startFrame": 972,
      "endFrame": 978
    },
    {
      "text": "N",
      "startFrame": 978,
      "endFrame": 985
    }
  ],
  [
    {
      "text": "mà?",
      "startFrame": 985,
      "endFrame": 991
    }
  ],
  [
    {
      "text": "N",
      "startFrame": 1011,
      "endFrame": 1016
    },
    {
      "text": "đang",
      "startFrame": 1016,
      "endFrame": 1022
    },
    {
      "text": "tìm",
      "startFrame": 1022,
      "endFrame": 1027
    },
    {
      "text": "cách",
      "startFrame": 1027,
      "endFrame": 1033
    }
  ],
  [
    {
      "text": "lấy",
      "startFrame": 1033,
      "endFrame": 1038
    },
    {
      "text": "lại",
      "startFrame": 1038,
      "endFrame": 1044
    },
    {
      "text": "tiền",
      "startFrame": 1044,
      "endFrame": 1049
    },
    {
      "text": "của",
      "startFrame": 1049,
      "endFrame": 1055
    }
  ],
  [
    {
      "text": "mình",
      "startFrame": 1055,
      "endFrame": 1060
    },
    {
      "text": "thôi.",
      "startFrame": 1060,
      "endFrame": 1066
    },
    {
      "text": "Cùng",
      "startFrame": 1066,
      "endFrame": 1071
    },
    {
      "text": "lắm",
      "startFrame": 1071,
      "endFrame": 1077
    }
  ],
  [
    {
      "text": "thì",
      "startFrame": 1077,
      "endFrame": 1082
    },
    {
      "text": "xử",
      "startFrame": 1082,
      "endFrame": 1088
    },
    {
      "text": "lý",
      "startFrame": 1088,
      "endFrame": 1093
    },
    {
      "text": "về",
      "startFrame": 1093,
      "endFrame": 1099
    }
  ],
  [
    {
      "text": "hành",
      "startFrame": 1099,
      "endFrame": 1104
    },
    {
      "text": "vi",
      "startFrame": 1104,
      "endFrame": 1109
    },
    {
      "text": "bắt",
      "startFrame": 1109,
      "endFrame": 1115
    },
    {
      "text": "giữ",
      "startFrame": 1115,
      "endFrame": 1120
    }
  ],
  [
    {
      "text": "người",
      "startFrame": 1120,
      "endFrame": 1126
    },
    {
      "text": "trái",
      "startFrame": 1126,
      "endFrame": 1131
    },
    {
      "text": "pháp",
      "startFrame": 1131,
      "endFrame": 1137
    },
    {
      "text": "luật",
      "startFrame": 1137,
      "endFrame": 1142
    }
  ],
  [
    {
      "text": "chứ.",
      "startFrame": 1142,
      "endFrame": 1148
    }
  ],
  [
    {
      "text": "tại",
      "startFrame": 1166,
      "endFrame": 1172
    },
    {
      "text": "sao",
      "startFrame": 1172,
      "endFrame": 1177
    },
    {
      "text": "lại",
      "startFrame": 1177,
      "endFrame": 1183
    },
    {
      "text": "thành",
      "startFrame": 1183,
      "endFrame": 1189
    }
  ],
  [
    {
      "text": "\"Bắt",
      "startFrame": 1189,
      "endFrame": 1195
    },
    {
      "text": "cóc",
      "startFrame": 1195,
      "endFrame": 1201
    },
    {
      "text": "nhằm",
      "startFrame": 1201,
      "endFrame": 1207
    },
    {
      "text": "chiếm",
      "startFrame": 1207,
      "endFrame": 1212
    }
  ],
  [
    {
      "text": "đoạt",
      "startFrame": 1212,
      "endFrame": 1218
    },
    {
      "text": "tài",
      "startFrame": 1218,
      "endFrame": 1224
    },
    {
      "text": "sản\"?",
      "startFrame": 1224,
      "endFrame": 1230
    }
  ],
  [
    {
      "text": "Đây",
      "startFrame": 1246,
      "endFrame": 1254
    },
    {
      "text": "mới",
      "startFrame": 1254,
      "endFrame": 1262
    },
    {
      "text": "chính",
      "startFrame": 1262,
      "endFrame": 1269
    },
    {
      "text": "là",
      "startFrame": 1269,
      "endFrame": 1277
    }
  ],
  [
    {
      "text": "điểm",
      "startFrame": 1277,
      "endFrame": 1285
    },
    {
      "text": "pháp",
      "startFrame": 1285,
      "endFrame": 1292
    },
    {
      "text": "lý",
      "startFrame": 1292,
      "endFrame": 1300
    },
    {
      "text": "cực",
      "startFrame": 1300,
      "endFrame": 1308
    }
  ],
  [
    {
      "text": "kỳ",
      "startFrame": 1308,
      "endFrame": 1315
    },
    {
      "text": "đáng",
      "startFrame": 1315,
      "endFrame": 1323
    },
    {
      "text": "chú",
      "startFrame": 1323,
      "endFrame": 1331
    },
    {
      "text": "ý",
      "startFrame": 1331,
      "endFrame": 1338
    }
  ],
  [
    {
      "text": "của",
      "startFrame": 1338,
      "endFrame": 1346
    },
    {
      "text": "Án",
      "startFrame": 1346,
      "endFrame": 1354
    },
    {
      "text": "lệ",
      "startFrame": 1354,
      "endFrame": 1361
    },
    {
      "text": "số",
      "startFrame": 1361,
      "endFrame": 1369
    }
  ],
  [
    {
      "text": "64",
      "startFrame": 1369,
      "endFrame": 1377
    },
    {
      "text": "năm",
      "startFrame": 1377,
      "endFrame": 1385
    },
    {
      "text": "2023.",
      "startFrame": 1385,
      "endFrame": 1392
    },
    {
      "text": "Thứ",
      "startFrame": 1392,
      "endFrame": 1400
    }
  ],
  [
    {
      "text": "nhất,",
      "startFrame": 1400,
      "endFrame": 1408
    }
  ],
  [
    {
      "text": "Dù",
      "startFrame": 1424,
      "endFrame": 1430
    },
    {
      "text": "giữa",
      "startFrame": 1430,
      "endFrame": 1436
    },
    {
      "text": "hai",
      "startFrame": 1436,
      "endFrame": 1443
    },
    {
      "text": "bên",
      "startFrame": 1443,
      "endFrame": 1449
    }
  ],
  [
    {
      "text": "có",
      "startFrame": 1449,
      "endFrame": 1455
    },
    {
      "text": "một",
      "startFrame": 1455,
      "endFrame": 1462
    },
    {
      "text": "khoản",
      "startFrame": 1462,
      "endFrame": 1468
    },
    {
      "text": "nợ",
      "startFrame": 1468,
      "endFrame": 1474
    }
  ],
  [
    {
      "text": "thật.",
      "startFrame": 1474,
      "endFrame": 1481
    },
    {
      "text": "nhưng",
      "startFrame": 1481,
      "endFrame": 1487
    },
    {
      "text": "nếu",
      "startFrame": 1487,
      "endFrame": 1494
    },
    {
      "text": "bạn",
      "startFrame": 1494,
      "endFrame": 1500
    }
  ],
  [
    {
      "text": "bắt",
      "startFrame": 1500,
      "endFrame": 1506
    },
    {
      "text": "giữ,",
      "startFrame": 1506,
      "endFrame": 1513
    },
    {
      "text": "trói,",
      "startFrame": 1513,
      "endFrame": 1519
    },
    {
      "text": "nhốt",
      "startFrame": 1519,
      "endFrame": 1525
    }
  ],
  [
    {
      "text": "hoặc",
      "startFrame": 1525,
      "endFrame": 1532
    },
    {
      "text": "dùng",
      "startFrame": 1532,
      "endFrame": 1538
    },
    {
      "text": "bạo",
      "startFrame": 1538,
      "endFrame": 1544
    },
    {
      "text": "lực",
      "startFrame": 1544,
      "endFrame": 1551
    }
  ],
  [
    {
      "text": "đối",
      "startFrame": 1551,
      "endFrame": 1557
    },
    {
      "text": "với",
      "startFrame": 1557,
      "endFrame": 1563
    },
    {
      "text": "con",
      "startFrame": 1563,
      "endFrame": 1570
    },
    {
      "text": "nợ",
      "startFrame": 1570,
      "endFrame": 1576
    }
  ],
  [
    {
      "text": "để",
      "startFrame": 1576,
      "endFrame": 1582
    },
    {
      "text": "gây",
      "startFrame": 1582,
      "endFrame": 1589
    },
    {
      "text": "áp",
      "startFrame": 1589,
      "endFrame": 1595
    },
    {
      "text": "lực.",
      "startFrame": 1595,
      "endFrame": 1601
    }
  ],
  [
    {
      "text": "rồi",
      "startFrame": 1601,
      "endFrame": 1608
    },
    {
      "text": "buộc",
      "startFrame": 1608,
      "endFrame": 1614
    },
    {
      "text": "chính",
      "startFrame": 1614,
      "endFrame": 1620
    },
    {
      "text": "họ,",
      "startFrame": 1620,
      "endFrame": 1627
    }
  ],
  [
    {
      "text": "gia",
      "startFrame": 1627,
      "endFrame": 1633
    },
    {
      "text": "đình",
      "startFrame": 1633,
      "endFrame": 1640
    },
    {
      "text": "hoặc",
      "startFrame": 1640,
      "endFrame": 1646
    },
    {
      "text": "người",
      "startFrame": 1646,
      "endFrame": 1653
    }
  ],
  [
    {
      "text": "thân",
      "startFrame": 1653,
      "endFrame": 1659
    },
    {
      "text": "phải",
      "startFrame": 1659,
      "endFrame": 1666
    },
    {
      "text": "giao",
      "startFrame": 1666,
      "endFrame": 1672
    },
    {
      "text": "tiền",
      "startFrame": 1672,
      "endFrame": 1679
    }
  ],
  [
    {
      "text": "thì",
      "startFrame": 1679,
      "endFrame": 1685
    },
    {
      "text": "mới",
      "startFrame": 1685,
      "endFrame": 1692
    },
    {
      "text": "thả",
      "startFrame": 1692,
      "endFrame": 1698
    },
    {
      "text": "người.",
      "startFrame": 1698,
      "endFrame": 1705
    }
  ],
  [
    {
      "text": "thì",
      "startFrame": 1720,
      "endFrame": 1725
    },
    {
      "text": "việc",
      "startFrame": 1725,
      "endFrame": 1730
    },
    {
      "text": "\"đòi",
      "startFrame": 1730,
      "endFrame": 1735
    },
    {
      "text": "nợ\"",
      "startFrame": 1735,
      "endFrame": 1740
    }
  ],
  [
    {
      "text": "đó",
      "startFrame": 1740,
      "endFrame": 1745
    },
    {
      "text": "không",
      "startFrame": 1745,
      "endFrame": 1750
    },
    {
      "text": "còn",
      "startFrame": 1750,
      "endFrame": 1755
    },
    {
      "text": "đơn",
      "startFrame": 1755,
      "endFrame": 1760
    }
  ],
  [
    {
      "text": "giản",
      "startFrame": 1760,
      "endFrame": 1765
    },
    {
      "text": "là",
      "startFrame": 1765,
      "endFrame": 1770
    },
    {
      "text": "một",
      "startFrame": 1770,
      "endFrame": 1775
    },
    {
      "text": "tranh",
      "startFrame": 1775,
      "endFrame": 1780
    }
  ],
  [
    {
      "text": "chấp",
      "startFrame": 1780,
      "endFrame": 1785
    },
    {
      "text": "tiền",
      "startFrame": 1785,
      "endFrame": 1790
    },
    {
      "text": "bạc",
      "startFrame": 1790,
      "endFrame": 1795
    },
    {
      "text": "nữa.",
      "startFrame": 1795,
      "endFrame": 1800
    }
  ]
];
