/**
 * V12Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan12.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan12.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V12Scene1, V12SCENE1_DURATION } from "./scenes/V12Scene1";
import { V12Scene2, V12SCENE2_DURATION } from "./scenes/V12Scene2";
import { V12Scene3, V12SCENE3_DURATION } from "./scenes/V12Scene3";
import { Captions11 } from "./scenes/shared11";

const T = 15;

export const MASTER12_DURATION =
  (V12SCENE1_DURATION + T) +
  (V12SCENE2_DURATION + T) +
  (V12SCENE3_DURATION + T) - 2 * T;

export const V12Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio11.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V12SCENE1_DURATION + T}>
        <V12Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V12SCENE2_DURATION + T}>
        <V12Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V12SCENE3_DURATION + T}>
        <V12Scene3 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions11 />
  </AbsoluteFill>
);
