/**
 * V13Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan13.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan13.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V13Scene1, V13SCENE1_DURATION } from "./scenes/V13Scene1";
import { V13Scene2, V13SCENE2_DURATION } from "./scenes/V13Scene2";
import { V13Scene3, V13SCENE3_DURATION } from "./scenes/V13Scene3";
import { V13Scene4, V13SCENE4_DURATION } from "./scenes/V13Scene4";
import { V13Scene5, V13SCENE5_DURATION } from "./scenes/V13Scene5";
import { V13Scene6, V13SCENE6_DURATION } from "./scenes/V13Scene6";
import { V13Scene7, V13SCENE7_DURATION } from "./scenes/V13Scene7";
import { V13Scene8, V13SCENE8_DURATION } from "./scenes/V13Scene8";
import { Captions13 } from "./scenes/shared13";

const T = 15;

export const MASTER13_DURATION =
  (V13SCENE1_DURATION + T) +
  V13SCENE2_DURATION +
  V13SCENE3_DURATION +
  (V13SCENE4_DURATION + T) +
  (V13SCENE5_DURATION + T) +
  (V13SCENE6_DURATION + T) +
  (V13SCENE7_DURATION + T) +
  (V13SCENE8_DURATION + T) - 5 * T;

export const V13Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio13.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V13SCENE1_DURATION + T}>
        <V13Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V13SCENE2_DURATION}>
        <V13Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V13SCENE3_DURATION}>
        <V13Scene3 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V13SCENE4_DURATION + T}>
        <V13Scene4 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V13SCENE5_DURATION + T}>
        <V13Scene5 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V13SCENE6_DURATION + T}>
        <V13Scene6 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V13SCENE7_DURATION + T}>
        <V13Scene7 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V13SCENE8_DURATION + T}>
        <V13Scene8 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions13 />
  </AbsoluteFill>
);
