/**
 * V14Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan14.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan14.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V14Scene1, V14SCENE1_DURATION } from "./scenes/V14Scene1";
import { V14Scene2, V14SCENE2_DURATION } from "./scenes/V14Scene2";
import { V14Scene3, V14SCENE3_DURATION } from "./scenes/V14Scene3";
import { V14Scene4, V14SCENE4_DURATION } from "./scenes/V14Scene4";
import { V14Scene5, V14SCENE5_DURATION } from "./scenes/V14Scene5";
import { V14Scene6, V14SCENE6_DURATION } from "./scenes/V14Scene6";
import { V14Scene7, V14SCENE7_DURATION } from "./scenes/V14Scene7";
import { Captions14 } from "./scenes/shared14";

const T = 15;

export const MASTER14_DURATION =
  (V14SCENE1_DURATION + T) +
  (V14SCENE2_DURATION + T) +
  (V14SCENE3_DURATION + T) +
  (V14SCENE4_DURATION + T) +
  (V14SCENE5_DURATION + T) +
  (V14SCENE6_DURATION + T) +
  (V14SCENE7_DURATION + T) - 6 * T;

export const V14Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio14.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V14SCENE1_DURATION + T}>
        <V14Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE2_DURATION + T}>
        <V14Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE3_DURATION + T}>
        <V14Scene3 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE4_DURATION + T}>
        <V14Scene4 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE5_DURATION + T}>
        <V14Scene5 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE6_DURATION + T}>
        <V14Scene6 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V14SCENE7_DURATION + T}>
        <V14Scene7 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions14 />
  </AbsoluteFill>
);
