/**
 * V15Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan15.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan15.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V15Scene1, V15SCENE1_DURATION } from "./scenes/V15Scene1";
import { V15Scene2, V15SCENE2_DURATION } from "./scenes/V15Scene2";
import { V15Scene3, V15SCENE3_DURATION } from "./scenes/V15Scene3";
import { V15Scene4, V15SCENE4_DURATION } from "./scenes/V15Scene4";
import { V15Scene5, V15SCENE5_DURATION } from "./scenes/V15Scene5";
import { V15Scene6, V15SCENE6_DURATION } from "./scenes/V15Scene6";
import { V15Scene7, V15SCENE7_DURATION } from "./scenes/V15Scene7";
import { V15Scene8, V15SCENE8_DURATION } from "./scenes/V15Scene8";
import { V15Scene9, V15SCENE9_DURATION } from "./scenes/V15Scene9";
import { V15Scene10, V15SCENE10_DURATION } from "./scenes/V15Scene10";
import { Captions14 } from "./scenes/shared14";

const T = 15;

export const MASTER15_DURATION =
  (V15SCENE1_DURATION + T) +
  (V15SCENE2_DURATION + T) +
  (V15SCENE3_DURATION + T) +
  (V15SCENE4_DURATION + T) +
  (V15SCENE5_DURATION + T) +
  (V15SCENE6_DURATION + T) +
  (V15SCENE7_DURATION + T) +
  (V15SCENE8_DURATION + T) +
  (V15SCENE9_DURATION + T) +
  (V15SCENE10_DURATION + T) - 9 * T;

export const V15Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio14.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V15SCENE1_DURATION + T}>
        <V15Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE2_DURATION + T}>
        <V15Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE3_DURATION + T}>
        <V15Scene3 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE4_DURATION + T}>
        <V15Scene4 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE5_DURATION + T}>
        <V15Scene5 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE6_DURATION + T}>
        <V15Scene6 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE7_DURATION + T}>
        <V15Scene7 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE8_DURATION + T}>
        <V15Scene8 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE9_DURATION + T}>
        <V15Scene9 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V15SCENE10_DURATION + T}>
        <V15Scene10 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions14 />
  </AbsoluteFill>
);
