/**
 * V16Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan16.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan16.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V16Scene1, V16SCENE1_DURATION } from "./scenes/V16Scene1";
import { V16Scene2, V16SCENE2_DURATION } from "./scenes/V16Scene2";
import { V16Scene3, V16SCENE3_DURATION } from "./scenes/V16Scene3";
import { V16Scene4, V16SCENE4_DURATION } from "./scenes/V16Scene4";
import { V16Scene5, V16SCENE5_DURATION } from "./scenes/V16Scene5";
import { V16Scene6, V16SCENE6_DURATION } from "./scenes/V16Scene6";
import { V16Scene7, V16SCENE7_DURATION } from "./scenes/V16Scene7";
import { V16Scene8, V16SCENE8_DURATION } from "./scenes/V16Scene8";
import { V16Scene9, V16SCENE9_DURATION } from "./scenes/V16Scene9";
import { V16Scene10, V16SCENE10_DURATION } from "./scenes/V16Scene10";
import { V16Scene11, V16SCENE11_DURATION } from "./scenes/V16Scene11";
import { V16Scene12, V16SCENE12_DURATION } from "./scenes/V16Scene12";
import { V16Scene13, V16SCENE13_DURATION } from "./scenes/V16Scene13";
import { Captions14 } from "./scenes/shared14";

const T = 15;

export const MASTER16_DURATION =
  V16SCENE1_DURATION +
  V16SCENE2_DURATION +
  V16SCENE3_DURATION +
  V16SCENE4_DURATION +
  (V16SCENE5_DURATION + T) +
  V16SCENE6_DURATION +
  V16SCENE7_DURATION +
  V16SCENE8_DURATION +
  V16SCENE9_DURATION +
  V16SCENE10_DURATION +
  V16SCENE11_DURATION +
  V16SCENE12_DURATION +
  (V16SCENE13_DURATION + T) - 1 * T;

export const V16Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio14.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V16SCENE1_DURATION}>
        <V16Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE2_DURATION}>
        <V16Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE3_DURATION}>
        <V16Scene3 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE4_DURATION}>
        <V16Scene4 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE5_DURATION + T}>
        <V16Scene5 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: T })} />
      <TransitionSeries.Sequence durationInFrames={V16SCENE6_DURATION}>
        <V16Scene6 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE7_DURATION}>
        <V16Scene7 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE8_DURATION}>
        <V16Scene8 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE9_DURATION}>
        <V16Scene9 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE10_DURATION}>
        <V16Scene10 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE11_DURATION}>
        <V16Scene11 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE12_DURATION}>
        <V16Scene12 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V16SCENE13_DURATION + T}>
        <V16Scene13 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions14 />
  </AbsoluteFill>
);
