/**
 * V17Master - master timeline, AUTO-GENERATED by assemble.py từ input/scene_plan17.json.
 *
 * Đừng sửa tay - sinh lại bằng:
 *   py -3 .claude/skills/vox-collage-video/scripts/assemble.py input/scene_plan17.json
 *
 * Luật rail (SKILL.md bước 7): TransitionSeries rút ngắn timeline đúng bằng
 * mỗi khoảng chồng, nên MỌI rail - kể cả rail ĐẦU - phải đệm đúng thời lượng
 * transition đứng sau nó; đệm thiếu rail đầu là mọi cảnh từ S2 trôi sớm nửa
 * giây so với audio của chính nó (lỗi đã ship một lần ở V10).
 */

import { AbsoluteFill, Audio, staticFile } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { V17Scene1, V17SCENE1_DURATION } from "./scenes/V17Scene1";
import { V17Scene2, V17SCENE2_DURATION } from "./scenes/V17Scene2";
import { V17Scene3, V17SCENE3_DURATION } from "./scenes/V17Scene3";
import { V17Scene4, V17SCENE4_DURATION } from "./scenes/V17Scene4";
import { V17Scene5, V17SCENE5_DURATION } from "./scenes/V17Scene5";
import { V17Scene6, V17SCENE6_DURATION } from "./scenes/V17Scene6";
import { V17Scene7, V17SCENE7_DURATION } from "./scenes/V17Scene7";
import { V17Scene8, V17SCENE8_DURATION } from "./scenes/V17Scene8";
import { V17Scene9, V17SCENE9_DURATION } from "./scenes/V17Scene9";
import { V17Scene10, V17SCENE10_DURATION } from "./scenes/V17Scene10";
import { Captions17 } from "./scenes/shared17";

const T = 15;

export const MASTER17_DURATION =
  V17SCENE1_DURATION +
  V17SCENE2_DURATION +
  V17SCENE3_DURATION +
  V17SCENE4_DURATION +
  V17SCENE5_DURATION +
  V17SCENE6_DURATION +
  V17SCENE7_DURATION +
  V17SCENE8_DURATION +
  V17SCENE9_DURATION +
  (V17SCENE10_DURATION + T) - 0 * T;

export const V17Master = () => (
  <AbsoluteFill style={{ backgroundColor: "#E7E3D9" }}>
    <Audio src={staticFile("audio17.mp3")} />

    <TransitionSeries>
      <TransitionSeries.Sequence durationInFrames={V17SCENE1_DURATION}>
        <V17Scene1 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE2_DURATION}>
        <V17Scene2 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE3_DURATION}>
        <V17Scene3 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE4_DURATION}>
        <V17Scene4 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE5_DURATION}>
        <V17Scene5 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE6_DURATION}>
        <V17Scene6 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE7_DURATION}>
        <V17Scene7 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE8_DURATION}>
        <V17Scene8 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE9_DURATION}>
        <V17Scene9 />
      </TransitionSeries.Sequence>
      <TransitionSeries.Sequence durationInFrames={V17SCENE10_DURATION + T}>
        <V17Scene10 />
      </TransitionSeries.Sequence>
    </TransitionSeries>

    {/* Phụ đề mount MỘT LẦN ở master, là anh em ĐỨNG SAU TransitionSeries -
        đặt bên trong thì nó bị cuốn theo từng lần chuyển cảnh. */}
    <Captions17 />
  </AbsoluteFill>
);
